### ISSUE TITLE
qBittorrent 4.0.3 update breaks integration

### ISSUE THREAD

**Issue by snblackout** [SchizoDuckie/DuckieTV#1020] opened 2018-01-10 17:52 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
Update qBittorrent to 4.0.3 and integration breaks.  Downgrade to 4.0.2 fixes.

**Attach any DuckieTV statistics or Developer Console logs if available**
None

**Comment by garfield69** [comment] 2018-01-10 17:55
Duplicate of #1009
Yes, qBt made a change in 4.0.3 that broke the DuckieTV qBt client interface. qbittorrent/qBittorrent@b827761 fixes this problem, which will be included in the next qBt release, whenever that gets published.
The problem cannot be fixed by DuckieTV, so 4.0.2 is the current compatible client.

**Closed as completed by garfield69** 2018-01-10 17:55 UTC
Labels: duplicate
