### ISSUE TITLE
uTorrent integration reset every reboot

### ISSUE THREAD

**Issue by lamaresh** [SchizoDuckie/DuckieTV#514] opened 2015-07-25 20:47 UTC
every time i open DukieTv for the first time in my chrome, uTorrent integration doesn't work.
In DukieTv i see uTorrent connected but current downloads are not shown. If i click the button "Remove uTorrent Integration" instead, the integration is refreshed (i will be asked again on utorrent client for the authorization).
I have to follow this procedure every reboot of my computer.

EDIT: my torrent client version is 3.4.3

**Comment by SchizoDuckie** [comment] 2015-07-26 19:02
Could you upload a recent backup to this ticket? I have one idea of what might the cause of this.

**Comment by lamaresh** [comment] 2015-07-28 16:08
what kind of backup? I've always had this problem even in older releases but I forgot to report it.

**Comment by SchizoDuckie** [comment] 2015-07-28 16:12
I'm just realizing that a backup is not neccesary (You can make one in settings -> backup -> create a backup though)

Please create a screenshot of the about page, scrolled down to the 'User Preferences on Local Storage' section like so:
![image](https://cloud.githubusercontent.com/assets/111710/8936717/1a07637e-3554-11e5-9e2c-46261c5a14d9.png)


(Pro tip, you can just press CTRL+V in the textbox here and it will upload it straight from your clipboard)

**Comment by lamaresh** [comment] 2015-07-28 16:20
![immagine](https://cloud.githubusercontent.com/assets/3250975/8936894/426aa262-3555-11e5-8e02-b068914151c4.png)

**Comment by lamaresh** [comment] 2015-07-28 16:20
today i've already reconfirmed utorrent authorization, by the way

**Comment by SchizoDuckie** [comment] 2015-07-28 17:18
allright, could you do one more thing for me:

Open DuckieTV
Hit F12 on your keyboard
open the console tab
execute the following code by pasting and hitting enter, and copy/ paste the result here

var a = JSON.parse(JSON.stringify(localStorage)); ['userPreferences','torrenting.hashList','trakt.token','trakttv.trending.cache','alarms'].map(function(key) { delete a[key]; }); console.log(JSON.stringify(a));

**Comment by garfield69** [comment] 2015-07-28 18:02
@SchizoDuckie  I'm thinking It would be useful if I changed the About Statistics section to dump the whole localStorage rather than just the userPreferences ?

**Comment by lamaresh** [comment] 2015-07-29 20:23
{"0.91fixoldpiratebay":"true","0.91migration":"Thu Jan 29 2015 10:09:57 GMT+0100 (ora solare Europa occidentale)","0.9migration":"Mon Jan 26 2015 21:27:44 GMT+0100 (ora solare Europa occidentale)","0.9updateallshows":"true","1.0migration":"Fri May 15 2015 14:13:50 GMT+0200 (ora legale Europa occidentale)","1.1migration":"Thu Jul 16 2015 16:52:24 GMT+0200 (ora legale Europa occidentale)","database.version.Episodes":"11","database.version.EventSchedule":"undefined","database.version.Seasons":"5","database.version.Series":"8","database.version.WatchList":"undefined","database.version.WatchListObject":"undefined","install.notify":"1.1.2","runtime.event":"{\"reason\":\"chrome_update\"}","torrenting.client":"uTorrent","trakt.username":"lamaresh87@gmail.com","trakttv.lastupdated":"1438201319494","trakttv.lastupdated.trending":"1437676202823","upgrade.notify":"1.1.2","utorrent.port":"10000","utorrent.token":"78824AE0C125C4A3E5C753AAFFA6E703FC42E30F"}

**Comment by SchizoDuckie** [comment] 2015-07-29 20:29
thanks for that! Unforunately that also doesn't provide any clue as to why this wouldn't work.

Would you mind downloading the latest .zip file from this repository, extracting it to a directory on your computer, and then loading that as an unpacked extension via chrome://extensions/  ?

Make sure to create a backup of your current DuckieTV installation first, just in case (by going to settings->backup -> create a backup), and then temporarily disable the webstore version of DuckieTV.

If you reboot after that, does the same behavior still exist? (I made some changes to the torrent client, There is now an auto-reconnect polling system)

**Comment by SchizoDuckie** [comment] 2015-07-29 20:31
@garfield69 awesome thanks!

**Comment by garfield69** [comment] 2015-07-29 20:38
I'm wondering if the issue in this ticket is not another manifestation of #507, stemming from uTorrent 3.4.3 changes which is common to both tickets ?

**Comment by SchizoDuckie** [comment] 2015-07-29 20:39
@garfield69 I've already done some testing with the new client. It's just an early initialisation of the controller (probably fixed locally already) The client  is connected and there are no problems with the key (in my 4.3.3 beta test)

**Comment by lamaresh** [comment] 2015-07-29 20:41
I did, tomorrow i'll let you know.
However a strage behaviour is that the "clear utorrent authorization" button actually prompt for an authorization request and not to an authorization deleting!

**Comment by SchizoDuckie** [comment] 2015-07-29 20:42
lamaresh, that means that the polling works. the clear authorization button
clears the auth token in DuckieTV. Meaning that the connection is created
and accepted for the rest of the requests.

**Comment by SchizoDuckie** [comment] 2015-07-29 20:44
The popup means that DuckieTV is trying to reconnect to your torrent client, and doesn't have an auth token stored yet. When you grant it permission, it uses that token.

One question more: You say that this happens when you start up your computer. If you just close chrome when your computer has been running for a bit, and then restart it. it does work?

**Comment by lamaresh** [comment] 2015-07-30 10:44
I understood the problem, it's quite simple!
If i start duckieTV and then i start uTorrent, integrations has to be promped manually.
If i start uTorrent and then i start DuckieTV everything works fine.
Can you confirm that?

**Comment by SchizoDuckie** [comment] 2015-07-30 10:57
That's correct,  and that has been fixed in the next release!
Op 30 jul. 2015 12:44 schreef "lamaresh" <notifications@github.com>:

**Comment by SchizoDuckie** [comment] 2015-08-06 22:31
I've fixed the autodownload launching too now even when your torrent client is started after you started duckietv, so i'm calling this fixed :)

**Closed by SchizoDuckie** 2015-08-06 22:31 UTC
Labels: bug - unable to replicate
