### ISSUE TITLE
Date not advancing automatically

### ISSUE THREAD

**Issue by Zxurian** [SchizoDuckie/DuckieTV#712] opened 2016-06-05 00:54 UTC
Just checked DuckieTV and 1 is showing as yellow, hasn't auto-gotten two episodes on the 2nd.

Computer is Win10x64 Pro, always on.

**Comment by garfield69** [comment] 2016-06-05 01:01
Click on the DuckieTV (i) About icon, scroll to the statistics section and report what the *Current Date And Time* is.

Please press the **F12** key to open the Development tools page, and click on the **console** tab to view the log.
Are there any error message of note ?

**Comment by Zxurian** [comment] 2016-06-05 01:07
Current Date and Time	Sun, 05 Jun 2016 01:05:36 GMT

There's several Erorrs of 
![img](http://i.imgur.com/5D8jZak.png)

but nothing specifically related to date/time

**Comment by garfield69** [comment] 2016-06-05 01:22
I take it you restarted DuckieTV since your first report, hence the date being current rather than still 1-jun-16.
the next time you spot the date being wrong on the calendar, check the about and see if the date has advanced.  Then look at the log, and track how many 409 or other errors there have been since DuckieTV was started. There may be a correlation between the logs being full and DuckieTV  having stopped processing.

Meanwhile I shall begin keeping my development DuckieTV and PC up overnight to see if I can replicate the problem.

**Comment by Zxurian** [comment] 2016-06-05 03:38
I haven't restarted DuckieTV at all. Teh current date and time show as current, but the calendar display still shows 1
![img](http://i.imgur.com/VUV6Hf8.png)

**Comment by garfield69** [comment] 2016-06-05 03:51
Oh, ok then. try using the calendar's next month button to view July then the previous button to go back to June. Still showing 1st of June in yellow now? (expecting it to show 5th).

Also, you might want to adjust the *auto-download period* in DuckieTV's *settings,torrent* side-panel to 3 or 5 days, to cover the longest period of time in between DuckieTV GUI visits, so that the auto-download can fetch the episodes it missed while being frozen.

If the calendar's yellow date is still showing 1st June, then restart DuckieTV.

**Comment by garfield69** [comment] 2016-06-05 05:38
I've looked at the code for our Transmission Client, and confirmed that error 409 is an error that we trap  to retry the request again. So this eliminates 409 from being an issue, as it is expected and handled.

Now, when midnight rolls over, DuckieTV is supposed to do an internal reset, in order to refresh the calendar's date.
The way to confirm that the roll over has happened for the day is to view the console log. But first, we need to turn on the timestamps.

So from the console log, click on the *settings* **Cog** icon, scroll down the General settings and set the *show timestamps* check-box.
![image](https://cloud.githubusercontent.com/assets/6933240/15803805/07d4e44c-2b44-11e6-9db0-629ef81f85ed.png)
![image](https://cloud.githubusercontent.com/assets/6933240/15803807/232e5700-2b44-11e6-9df1-5002256b5f6f.png)

Then, assuming that the console does not have the *preserve log* check-box enabled, scroll back to the top of the log.
The very first message should be the **Quack!** from the utilities script. And the Time-stamp should be today's date.
![image](https://cloud.githubusercontent.com/assets/6933240/15803809/3cf83a20-2b44-11e6-8994-80b61e289431.png)


If it is not, then that means the midnight rolll-over did not happen.

If the *preserve log* checkbox has been enabled, then you obviously will be able to scroll back further for every additional day that DuckieTV has been active, and at midnight you should see a correspnding **Quack!** message if everything is working as it supposed to.

So take a look at your log please ,and let me know what you find. Thanks.

**Comment by Zxurian** [comment] 2016-06-05 06:34
timestamps enabled, Iinital Quack is from when the last time I restarted it was, `2016-06-01:17.35.16.594`

no **Quack!** message on the log since the initial one at that timestamp

showing rollover with no Quack
![img](http://i.imgur.com/XNO7STq.png)

**Comment by garfield69** [comment] 2016-06-05 07:04
OK. so the next nightly build (build date 5th june 2016) sometime tomorrow in about 14 hours, will contain a few debug messages to start looking at what is preventing the reload from happening.

So once the build is available, download it and let see what happens.
Once midnight rolls over on the active new build, you'll see additional messages in the log around that time.

BTW, this new build will also contain the option to switch the Global Include List from ANY to ALL.

**Comment by Zxurian** [comment] 2016-06-05 07:10
sounds awesome. Any notification for when the new build is available, or
just checking when it's available?

**Comment by garfield69** [comment] 2016-06-05 07:47
Nightly are build around 09:07 GMT at https://github.com/DuckieTV/Nightlies/releases every day.

**Comment by garfield69** [comment] 2016-06-05 07:49
oops, that wrong. 09:07 GMT+12 is the time I get when I look at the time stamp at that address. You will get your own local time presented if you mouse over the time. Sorry.

**Comment by garfield69** [comment] 2016-06-06 17:31
The good news is that I have been able to replicate your problem in my test environment. So now the fun begins.

**Comment by Zxurian** [comment] 2016-06-06 17:48
lol, good times.
do you still need me to download the nightly?

**Comment by garfield69** [comment] 2016-06-06 17:52
Only if you want to start using the Global Includes List ANY/ALL setting
option for your personal usage/testing. 

 

  _____

**Comment by garfield69** [comment] 2016-06-07 21:14
OK. So the latest nightly https://github.com/DuckieTV/Nightlies/releases/tag/nightly-06072016 should fix the problem of the calendar not updating overnight.
@shadycady regarding the issue you raised in ticket #696, this fix applies to you too.
Closing ticket. Should either of you report that the problem continues, I'll reopen it.

**Closed by garfield69** 2016-06-07 21:14 UTC
Labels: 3 - Done, bug, Testing Completed

**Comment by Zxurian** [comment] 2016-06-08 13:28
downloading tonight and i'll re-open if it pops up again

**Comment by shadycady** [comment] 2016-06-09 06:17
Yup appears to have been fixed. Calendar updates correctly.
