### ISSUE TITLE
Backup not restoring shows tried FAQ

### ISSUE THREAD

**Issue by shellig** [SchizoDuckie/DuckieTV#1402] opened 2023-11-19 08:28 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...DuckieTV - 'Browser Action' mode - 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly
3023.11.1.1075

**What is your Operating System (Windows, MacOSx, Linux)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...New nightly - won't load from TraktTV or backup - tried "https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#i-cant-add-a-series-and-there-is-nothing-in-the-calendar"

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2023-11-19 16:37
read https://github.com/SchizoDuckie/DuckieTV/issues/1399#issuecomment-1789353212
closing as duplicate of #1399

**Closed as completed by garfield69** 2023-11-19 16:37 UTC

**Comment by garfield69** [comment] 2023-11-21 03:51
P.S. I've updated that wiki to include the websql override.
And of course, if this does not solve the problem please report back and we can re-open the ticket and do more diag.
