### ISSUE TITLE
Mac OS X bug in menu bar

### ISSUE THREAD

**Issue by recoi1er** [SchizoDuckie/DuckieTV#715] opened 2016-06-08 02:56 UTC
![screen shot 2016-06-07 at 7 55 46 pm](https://cloud.githubusercontent.com/assets/19810634/15881309/d7af020a-2ce9-11e6-8c01-036927ddf632.jpg)

More and more of these ducks keep popping up on OS X 10.11.5.

**Comment by garfield69** [comment] 2016-06-08 03:49
Are you using the Mac DuckieTV standalone version 1.1.3 by any chance?
If you are, I recommend installing one of the nightly development versions, such as https://github.com/DuckieTV/Nightlies/releases/tag/nightly-06042016
it contains many bug fixes, including one for the systray icon duplication on Mac.

If it does not solve your problem please let me know so I can reopen this ticker and look into the matter further.

Closed as dupe of #701

**Closed by garfield69** 2016-06-08 03:49 UTC
Labels: duplicate
