### ISSUE TITLE
Chromium 119+ has Web SQL disabled, which is the database Dtv needs to store shows. How to fix?

### ISSUE THREAD

**Issue by DirtySkeMe** [SchizoDuckie/DuckieTV#1399] opened 2023-10-31 18:40 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Chrome Extension Browser Action
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
nightly-202308131147 (8/13/2023)

**What is your Operating System (Windows, MacOSx, Linux)**
Chromebook

**Describe the problem you are having and steps to reproduce if available**

Last week i updated my Chromebook i'm on the beta Channel for the updates then all my show disapear since I tried to reset,reinstall,... if i use my backup it will load my backup until it crash but when loading there is no thumbnails on the shows and if i do it with Trakt same thing even if i just go to the + add show it will show the name but no thumbnails too I think it some new security they gone add in the next chrome since I tried to install Kiwi browser but it crash when loading my backup tried with Trakt samething since I use a server with Ubuntu and a standalone thru VNC not the best but if someone have a idea to help i'll forever be thankfull

an example of the show https://ibb.co/RPv8nMF

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2023-10-31 18:46
I don't have a chromebook, but have you looked at the session log to see if there are errors related to fetching the images?
press **F12** to open the devtools and click on the **console** tab to view the session log.

**Comment by DirtySkeMe** [comment] 2023-10-31 18:54
deps.js:92 DuckieTV quack!






app.js:8459 Registering torrent client: Aria2
app.js:8459 Registering torrent client: BiglyBT
app.js:8459 Registering torrent client: Deluge
app.js:8459 Registering torrent client: qBittorrent (pre3.2)
app.js:8459 Registering torrent client: qBittorrent 3.2+
app.js:8459 Registering torrent client: Ktorrent
app.js:8459 Registering torrent client: rTorrent
app.js:8459 Registering torrent client: Tixati
app.js:8459 Registering torrent client: Transmission
app.js:8459 Registering torrent client: tTorrent
app.js:8459 Registering torrent client: uTorrent Web UI
app.js:8459 Registering torrent client: Vuze
app.js:8459 Registering torrent client: None
app.js:11502 SettingsService.changeLanguage en_us en_us
app.js:8389 The next autoBackup is scheduled for Wed Nov 01 2023 20:10:38 GMT+0100 (Central European Standard Time)
app.js:10939 Next SNRT update is due after  Tue Oct 31 2023 20:09:45 GMT+0100 (Central European Standard Time)
app.js:10940 Fetched SNRT name and date exceptions, and TraktTvdbXref from localStorage.
app.js:11091 Initializing Xross Entity Mapping (https://thexem.info/) service for Scene Name episode format.
app.js:11019 Fetched localstorage Xem series list:  Array(1171)
app.js:11021 Fetched localstorage Xem series alias map: Object
app.js:11925 Enabling torrent auto-stop!
app.js:16585 Fetched trackers fall back list from localStorage.
app.js:16377 Updating torrent search engine ThePirateBay
app.js:16377 Updating torrent search engine 1337x
app.js:16377 Updating torrent search engine ETag
app.js:16377 Updating torrent search engine EXT
app.js:16377 Updating torrent search engine EzTV.ag
app.js:16377 Updating torrent search engine Idope
app.js:16377 Updating torrent search engine IsoHunt2
app.js:16377 Updating torrent search engine KATws
app.js:16377 Updating torrent search engine Knaben
app.js:16377 Updating torrent search engine LimeTorrents
app.js:16377 Updating torrent search engine Nyaa
app.js:16377 Updating torrent search engine ShowRSS
app.js:16377 Updating torrent search engine TorrentDownloads
app.js:16377 Updating torrent search engine TGx
app.js:11669 Register new storage sync target! TraktTVStorageSyncTarget
bebasneue_regular-webfont.ttf:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
app.js:12125 Deluge connected!
app.js:19209 Not performing TraktTV update check. Already done within the last 1 hour(s).
2app.js:19222 Not performing TraktTV trending update check. Last done Mon Oct 30 2023 20:09:50 GMT+0100 (Central European Standard Time)
app.js:19205 TraktTV update check completed. 0 shows updated since Tue Oct 31 2023 17:21:42 GMT+0100 (Central European Standard Time)

**Comment by garfield69** [comment] 2023-10-31 19:03
so apart from the font not loading [edit] (actually I'm not sure that net::ERR_FILE_NOT_FOUND message is the font but something else), you don't see any error messages while using the favourites page and seeing the posters spin their wheels?
but you can see the calendar day schedule ok?
what about clicking on a series poster, does that take you to the details page?
can you go to the **about** page by clicking the (i) icon on the bottom left of the calendar page and scrolling to the bottom.
what you you get for the number of records in the DB sections?

**Comment by DirtySkeMe** [comment] 2023-10-31 19:26
https://ibb.co/SJqv0mq
https://ibb.co/80tc6wV
https://ibb.co/x8vFg5J
https://ibb.co/L6g9LNc
https://ibb.co/F4z413w
https://ibb.co/0frL2SC
https://ibb.co/MBm4PN6

**Comment by garfield69** [comment] 2023-10-31 19:37
the last image is blank?
I'd like a view of the top of the about page, and one of the bottom.
IF you switch the calendar to month view you don't see any boxes with episodes? (click the V under the November to switch modes.)

**Comment by DirtySkeMe** [comment] 2023-10-31 19:44
https://ibb.co/Ph4tJFM
https://ibb.co/GFrB3qm

**Comment by garfield69** [comment] 2023-10-31 19:51
ok lets try a different approach.
can you go to one of the series that you have which you know have episodes on this month, and view the seasons page and the latest episodes page?
if you click on that series details  REFRESH button and then check the console log do you see any activity errors etc?

**Comment by DirtySkeMe** [comment] 2023-10-31 20:00
can't do it since there are no favorite
https://ibb.co/4dv3wNw

i'm trying to restore my backup using the new tab same thing
https://ibb.co/gdgFSvb

i'm sure it's chrome They changed some security thing

**Comment by garfield69** [comment] 2023-10-31 20:09
And while you are doing the restore, there is nothing showing up in the console log showing activity or errors?
very strange.
Not sure where to go from here. I shall do some research and see if I can come up with something.

**Comment by DirtySkeMe** [comment] 2023-10-31 20:13
```
deps.js:92 DuckieTV quack!
app.js:8459 Registering torrent client: Aria2
app.js:8459 Registering torrent client: BiglyBT
app.js:8459 Registering torrent client: Deluge
app.js:8459 Registering torrent client: qBittorrent (pre3.2)
app.js:8459 Registering torrent client: qBittorrent 3.2+
app.js:8459 Registering torrent client: Ktorrent
app.js:8459 Registering torrent client: rTorrent
app.js:8459 Registering torrent client: Tixati
app.js:8459 Registering torrent client: Transmission
app.js:8459 Registering torrent client: tTorrent
app.js:8459 Registering torrent client: uTorrent Web UI
app.js:8459 Registering torrent client: Vuze
app.js:8459 Registering torrent client: None
app.js:11502 SettingsService.changeLanguage en_us en_us
app.js:8389 The next autoBackup is scheduled for Thu Nov 02 2023 19:58:33 GMT+0100 (Central European Standard Time)
app.js:10939 Next SNRT update is due after  Wed Nov 01 2023 19:58:14 GMT+0100 (Central European Standard Time)
app.js:10940 Fetched SNRT name and date exceptions, and TraktTvdbXref from localStorage.
app.js:11091 Initializing Xross Entity Mapping (https://thexem.info/) service for Scene Name episode format.
app.js:11019 Fetched localstorage Xem series list:  Array(1172)
app.js:11021 Fetched localstorage Xem series alias map: Object
app.js:11925 Enabling torrent auto-stop!
app.js:16585 Fetched trackers fall back list from localStorage.
app.js:16377 Updating torrent search engine ThePirateBay
app.js:16377 Updating torrent search engine 1337x
app.js:16377 Updating torrent search engine ETag
app.js:16377 Updating torrent search engine EXT
app.js:16377 Updating torrent search engine EzTV.ag
app.js:16377 Updating torrent search engine Idope
app.js:16377 Updating torrent search engine IsoHunt2
app.js:16377 Updating torrent search engine KATws
app.js:16377 Updating torrent search engine Knaben
app.js:16377 Updating torrent search engine LimeTorrents
app.js:16377 Updating torrent search engine Nyaa
app.js:16377 Updating torrent search engine ShowRSS
app.js:16377 Updating torrent search engine TorrentDownloads
app.js:16377 Updating torrent search engine TGx
app.js:11669 Register new storage sync target! TraktTVStorageSyncTarget
app.js:12125 Deluge connected!
app.js:19209 Not performing TraktTV update check. Already done within the last 1 hour(s).
app.js:19222 Not performing TraktTV trending update check. Last done Tue Oct 31 2023 19:58:20 GMT+0100 (Central European Standard Time)
deps.js:2333 Error: [$rootScope:inprog] http://errors.angularjs.org/1.7.3/$rootScope/inprog?p0=%24apply
    at deps.js:2213:168
    at q (deps.js:2352:171)
    at m.$digest (deps.js:2357:46)
    at app.js:6935:20
    at m.$broadcast (deps.js:2363:98)
    at $scope.refreshDatabase (app.js:2231:18)
    at deps.js:2472:354
    at e (deps.js:2403:262)
    at m.$eval (deps.js:2360:239)
    at m.$apply (deps.js:2360:482)
(anonymous) @ deps.js:2333
app.js:2053 Import backup! m
app.js:2073 Backup read! Object
api.trakt.tv/shows/2177/seasons/19/episodes?extended=full:1 

       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
deps.js:2333 Possibly unhandled rejection: Error -1:
(anonymous) @ deps.js:2333
api.trakt.tv/shows/2177/seasons/20/episodes?extended=full:1 

       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
api.trakt.tv/shows/2177/seasons/21/episodes?extended=full:1 

[repeated 780 times for the other records]

       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
api.trakt.tv/shows/174462/seasons/1/episodes?extended=full:1 

       Failed to load resource: net::ERR_INSUFFICIENT_RESOURCES
deps.js:2333 Possibly unhandled rejection: Error -1:
(anonymous) @ deps.js:2333
deps.js:1328 Query error:  {guid: 'c0fd15df-f1a2-d95c-f313-fa687cbc2705-246', error: {…}}
queryError @ deps.js:1328
```

**Comment by DirtySkeMe** [comment] 2023-10-31 20:32
i'm going to try an older version

**Comment by DirtySkeMe** [comment] 2023-10-31 20:54
so far June nightly show the thumbnails in + add shows now i gone try to upload my backup now

**Comment by DirtySkeMe** [comment] 2023-10-31 21:24
i'm done for today i'll try tomorrow again i'll let you know if anything new

**Comment by garfield69** [comment] 2023-11-01 00:12
the issue is that beginning with chromium 119 WEB SQL has been removed.
WebSQL is the database that Dtv uses to store all the show data it fetches from trakt.tv
https://developer.chrome.com/blog/deprecating-web-sql/
End of the road for Dtv on browser.
all that will be left is the standalone Dtv where we can lock in the last working chromium 118.
Unfortunately Dtv Standalone does not work on chromebook as the 3rd party product NWJS which Dtv uses to allow it to run its Javascript on a standalone mode only supports windows, linux and OSx.

**Comment by DirtySkeMe** [comment] 2023-11-01 00:25
thank you for your help i'll try to make it work with Kiwi Browser (on my Chromebook) until they do update the chromium to 119 lucky i have it on a Ubuntu on a server as a standalone
cool now you know a lot of people gone have the same issue

**Comment by garfield69** [comment] 2023-11-01 17:21
Apparently, you can re-enable the WebSQL support on chromium 119 by using this override flag:
`chrome://flags/#web-sql-access`
then clicking **enable** and **relaunch**.
I do not know for how long this bypass will be available, so expect it to vanish by version 123.

**Comment by DirtySkeMe** [comment] 2023-11-01 17:54
Thanks 🙏🏿👍🏿

**Comment by yeralin** [comment] 2023-11-03 00:25
Had the same issue, enabling `chrome://flags/#web-sql-access` flag worked perfectly!

Maybe let's keep the issue open for visibility?

**Comment by DirtySkeMe** [comment] 2023-11-03 00:27
> Had the same issue, enabling `chrome://flags/#web-sql-access` flag worked perfectly!
> 
> Maybe let's keep the issue open for visibility?

Which OS ?

**Comment by syphondog3** [comment] 2023-11-13 17:57
> > Had the same issue, enabling `chrome://flags/#web-sql-access` flag worked perfectly!
> > Maybe let's keep the issue open for visibility?

Thank you for finding this workaround. I hope Google doesn't get rid of it, like they did the downloads at bottom option.

Thank you to the community!

**Comment by KieranDevvs** [comment] 2023-11-16 19:00
> > > Had the same issue, enabling `chrome://flags/#web-sql-access` flag worked perfectly!
> > > Maybe let's keep the issue open for visibility?
> 
> Thank you for finding this workaround. I hope Google doesn't get rid of it, like they did the downloads at bottom option.
> 
> Thank you to the community!

Its already marked as deprecated and is being deleted in 123.
![image](https://github.com/SchizoDuckie/DuckieTV/assets/21192520/eb6846b8-fc80-40c2-af3b-0d0724ddde89)

**Comment by KieranDevvs** [comment] 2023-11-16 23:27
> the issue is that beginning with chromium 119 WEB SQL has been removed. WebSQL is the database that Dtv uses to store all the show data it fetches from trakt.tv https://developer.chrome.com/blog/deprecating-web-sql/ End of the road for Dtv on browser. all that will be left is the standalone Dtv where we can lock in the last working chromium 118. Unfortunately Dtv Standalone does not work on chromebook as the 3rd party product NWJS which Dtv uses to allow it to run its Javascript on a standalone mode only supports windows, linux and OSx.

This issue should not be closed as the alternative SQL web api is `IndexedDB` which offers async IO.
If DuckyTV wishes to continue, maintainers need to port all access of `WebSQL` to `IndexedDB`

**Comment by garfield69** [comment] 2024-04-19 05:00
End of the line for DuckieTV as a Browser Extension.
Starting with Chromium 124,  WEB SQL is no longer available.
Only the Standalone DuckieTV now remains.

**Closed as completed by garfield69** 2024-04-19 05:00 UTC
Labels: question
