### ISSUE TITLE
[nightly-202401180913] can't move window using title bar

### ISSUE THREAD

**Issue by ilike2burnthing** [SchizoDuckie/DuckieTV#1406] opened 2024-01-19 04:01 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Nightly 202401180913

**What is your Operating System (Windows, MacOSx, Linux)**
Windows 10

**Describe the problem you are having and steps to reproduce if available**
- install and run nightly-202311011754
- move mouse to DuckieTV's title bar
- click, hold, and drag to move window
---
- install and run nightly-202401180913
- move mouse to DuckieTV's title bar - mouse icon changes to move icon (4 arrows)
- click, hold, and attempt to drag to move window, but fail
---
Can maximise, restore, and minimise; can use Windows key plus arrow keys to snap window; and confirmed in Windows Sandbox that a clean install behaves the same.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2024-01-19 04:14
There is no title bar as the window is frameless. 
Those min/max/close buttons on the top right are not the win10 frame buttons but glyphicon hardcoded in the tabs.html
I forget the reason  we dont use regular windows, I expect it was to gain more real-estate for presentation.

**Comment by ilike2burnthing** [comment] 2024-01-19 04:24
Ah kk, well the top of the window then. It was previously clickable and dragable, it no longer is as of yesterday's release.

**Comment by garfield69** [comment] 2024-01-19 04:28
ok. i did switch NWJS to 0.83.0 (chromium 120) from 0.81.1 (chromium 118) in the latest build so it could be a fallout or regression from that.
I'll see if there is any tickets open for it on nwjs but lately there has been little ticket solving there, other than the regular bumping of version to import the latest nodejs and chromium updates.

**Comment by garfield69** [comment] 2024-01-19 04:30
possible that https://github.com/nwjs/nw.js/issues/8153 is relevant.

**Comment by ilike2burnthing** [comment] 2024-01-19 04:36
Looks it.

**Comment by garfield69** [comment] 2024-01-19 04:40
I'll test reverting the nwjs back to 0.81 and check that the installer does not cause an issue on my sandbox for ubuntu and win10.
Sometimes upgrading chromium can cause backward compatibility error messages, so touch wood that we don't get one of those situations where we have to wait for the nwjs ticket to be solved with the next nwjs release.

**Comment by garfield69** [comment] 2024-01-19 05:25
https://github.com/DuckieTV/Nightlies/releases/tag/nightly-202401191752

**Comment by ilike2burnthing** [comment] 2024-01-19 05:29
Ta, working well.

**Comment by garfield69** [comment] 2024-02-13 06:28
https://github.com/nwjs/nw.js/issues/8153#issuecomment-1940039796

Awaiting the release of NWJS 0.85.0 with chromium 122 for the window drag fix.

**Comment by garfield69** [comment] 2024-04-23 04:42
should be resolved with https://github.com/DuckieTV/Nightlies/releases/tag/Nightly-202404110853 which uses NWJS 0.86 with Chromium 123

**Closed as completed by garfield69** 2024-04-23 04:42 UTC
