### ISSUE TITLE
Added new shows, DuckieTV Calendar 1.1.5 shows Green Highlighting

### ISSUE THREAD

**Issue by syphondog3** [SchizoDuckie/DuckieTV#979] opened 2017-10-14 18:38 UTC
I updated to 1.1.5 and added new shows within DuckieTV last night. These new shows added are now highlighted in green (see picture).

I can't figure out how to get rid of it from being highlighted! 

I am using Google Chrome on Windows 10. Only started happening after I updated to 1.1.5

Thanks =)
![screenshot 2017-10-14 14 35 36](https://user-images.githubusercontent.com/32645908/31578340-63a2c7a0-b0ed-11e7-9823-22e068e448a4.png)

**Comment by garfield69** [comment] 2017-10-14 18:55
did you add them via the duckietv add-new-show or did you import them from trakt.tv ?

when an episode is highlighted in green, this indicates the show has been downloaded.
DuckieTV has always had this feature.

**Comment by syphondog3** [comment] 2017-10-14 19:03
I added some from DuckieTV. Carpool Karaoke would not be found properly in DuckieTV. So I had go to Trakt.TV to add that.

I don't download episodes so it is strange that it is happening to many shows.

Is there a way to check to make sure it knows I don't download shows? Some setting? I am going to untoggle all the ones marked green now by deselecting "mark as saved" icon.

Want to make sure future shows aren't default marked as downloaded.

**Comment by syphondog3** [comment] 2017-10-14 19:05
ahhh - auto-download was enabled. I just disabled it. Was this the cause?

**Comment by garfield69** [comment] 2017-10-14 19:15
When importing shows from Trakt.tv, then any episodes on your Trakt account that you have marked as *collected* will be marked as *downloaded* on DuckieTV.      
If you had the *auto-download* enabled then DuckieTV would search for episodes torrents and send them to your connected torrent client.      
If you don't have an active torrent client, then the episode status would not change on DuckieTV.
But if your client is active, then yes, after the torrent client has finished downloading, the episode will be marked as *downloaded* on DuckietV.     
Check you torrent client for activity, and check if any episodes have been downloaded. You may want to remove those files and clean up.

Auto-download is not enabled by default, so if it was active you had to have turned it on in settings....

Manually setting any episodes to *not-downloaded* will remove the green highlight.

**Comment by syphondog3** [comment] 2017-10-14 19:17
Weird! I don't have a torrent client installed on my computer.

There are so many green highlighted ones going very far back. Is there a master setting to say "mark ALL shows as NOT downloaded"?

Otherwise I have to do a lot of manually clicking of "not downloaded"

**Comment by garfield69** [comment] 2017-10-14 19:34
It probably all happened when you added *carpool Karaoke* to your Trakt.tv account and did a DuckieTV Trakt.tv import. The import is for ALL shows on your Trakt.tv account, not just the new one you recently added to the account.     

Batch un-marking of the downloaded flag is not something we have had to consider before.       
But there is a hack you can try if you want:
1. first, make a backup by navigating to the DuckieTV *Settings, Backup* side panel, and using the *create database backup* button.
2. zip the backup file and drag and drop it here.
3. I will edit the file and remove all the downlaoded and watched-at flags, and post the file back here.
4. OR you can do this yourself using a good plain text editor it you know how.
5. Once the backup is prepared, navigate DuckieTV to the *Settings, backup* side panel and scroll down to the *import a backup* section.
6. tick the *wipe before import* check box
7. load the backup using the *choose a backup to load* button.

**Comment by garfield69** [comment] 2017-10-14 19:50
Also, going back the the cause of all the in the first place, what problem did you have looking for *Carpool Karaoke* using the DuckieTV add-a-show search?
I get four shows when I try this:
![image](https://user-images.githubusercontent.com/6933240/31578785-a2658418-b184-11e7-9848-bac47a054404.png)
and clicking on the centre of each poster will show details side panel to help you determine which show is the one you want. 
What do you get when you tried this?

**Comment by syphondog3** [comment] 2017-10-14 19:50
Here is my database  -- thank you!
[DuckieTV 10-14-17 (1).zip](https://github.com/SchizoDuckie/DuckieTV/files/1384927/DuckieTV.10-14-17.1.zip)

**Comment by syphondog3** [comment] 2017-10-14 19:52
Yes, I initially clicked the first one -- but then regretted it because I was too trigger happy. None of those 4, as you see, have the poster loaded.

When I went to Trakt.TV, there are a ton of search results, but one of them at the bottom had the proper poster -- so I added it there. I can see why this happened because I added it twice -- once through duckie and then imported it through Trakt.

But it is stange that other shows like Young Sheldon, and APV, and Genius, amongst many more, got marked as downloaded.

When I added Carpool Karaoke, I also added MacGyver and SuperVet through TraktTV.

**Comment by garfield69** [comment] 2017-10-14 20:27
Here you are, [DuckieTV 10-14-17 (no download flags).zip](https://github.com/SchizoDuckie/DuckieTV/files/1384949/DuckieTV.10-14-17.no.download.flags.zip)

The lack of a poster on the add-a-show panel is not an indication that there is something wrong with the show.      
We used to use Trakt.TV's API to download the posters, but they stopped providing that service when they found it cost too much to support. So now Trakt.TV show posters only for their web online site, and not the API.
So we had to switch to using FanArt to get our posters, but they don't have a complete collection, and are slower to update with new ones, so that is why some posters are missing when you look for new shows with DuckieTV.

Avoid using the Trakt.TV import unless you have your Trakt.TV account properly curated, otherwise this will happen again if you do another DuckieTV Trakt import.

**Comment by syphondog3** [comment] 2017-10-15 01:14
Ok, so I wiped it and when I try to import your new DB, it get stuck on the "loading, please wait" screen 

![screenshot 2017-10-14 21 14 07](https://user-images.githubusercontent.com/32645908/31580656-a52aaa4e-b124-11e7-8399-14f3bb7d7bf0.png)

**Comment by syphondog3** [comment] 2017-10-15 01:19
How do I properly curate my Trakt.TV account? Sorry if that is a dumb question! Honestly, the green bar thing has never ever happened before! I just disabled all torrent functionality.

**Comment by syphondog3** [comment] 2017-10-15 01:38
OK - so after DECOUPLING this function, "**When this setting is enabled, pressing an episode's 'mark as watched' button will also set it as 'downloaded'. And pressing the 'mark as not downloaded' button will also set the episode as 'not watched'. Disabling this setting will decouple this functional pairing.**

It seems to have gone away (the green highlighting). Is that correct?

I did this on an imported Trakt.TV database.

For whatever reason, even after 30 mins, your edited DB was giving it problems =/

**Comment by garfield69** [comment] 2017-10-15 02:53
>Ok, so I wiped it and when I try to import your new DB, it get stuck on the "loading, please wait" screen     

Urg. something has glitched with the db. the best way to recover is:

1. Visit the `chrome://extensions/` on your browser,
2. and use the trash-bin icon to remove your DuckieTV extension.
3. Then shutdown your Browser completely and start it up again (this gives Chrome the chance to clean up the dataspace)
4. Now install the DuckieTV extension from https://chrome.google.com/webstore/detail/cdfkaloficjmdjbgmckaddgfcghgidei (Action mode)
5. or https://chrome.google.com/webstore/detail/hkbamkappmgfjjahmnlngibomenmbbdf (New Tab mode)
6. And Start the extension
7. Wait a minute or two for everything to settle down
8. And at the *You have no series yet!* page, import your backup to restore your DuckieTV series and Settings. 

let me know how it goes.

**Comment by garfield69** [comment] 2017-10-15 03:31
Huh. Wait. I just tested the backup again, and I've spotted a problem. Please wait while I fix the backup and upload a replacement.
Sorry about that.
I thought I had tested this file, but I must have made a mistake :-(

**Comment by garfield69** [comment] 2017-10-15 03:53
I am really sorry about that. I fixed the problem with the backup, and here is the replacement, which I have tested on my Sandbox.     
[Valid DuckieTV 10-14-17 (no download flags).zip](https://github.com/SchizoDuckie/DuckieTV/files/1385171/Valid.DuckieTV.10-14-17.no.download.flags.zip)
So repeat the Import with wipe and you should get all your shows and settings restored, with all episodes not marked as downloaded.
Let me know how you go.

**Comment by garfield69** [comment] 2017-10-17 07:09
>OK - so after DECOUPLING this function, "When this setting is enabled, pressing an episode's 'mark as watched' button will also set it as 'downloaded'. And pressing the 'mark as not downloaded' button will also set the episode as 'not watched'. Disabling this setting will decouple this functional pairing.
>It seems to have gone away (the green highlighting). Is that correct?

Not quite.    
Yes, this setting should help you when you manually set episodes to watched, by not marking them automatically to downloaded, which is certainly something you could make use of.
However, I found some bugs in the code, which I fixed with #983, which will be included in the next Nightly built in about 12 hours from now.

**Comment by syphondog3** [comment] 2017-10-20 15:17
OK! I tried your new database on a different computer (same account) that had the green color issue again.

Your database worked fine.

Going forward, what do I do in a situation like Carpool Karaoke where I don't know which one to pick when searching through DuckieTV since the posters don't load?

Thank you, @garfield69 !!!!!

**Comment by garfield69** [comment] 2017-10-20 17:36
>Going forward, what do I do in a situation like Carpool Karaoke where I don't know which one to pick when searching through DuckieTV since the posters don't load?      

If you click on the centre of each poster in turn, the side panel will give you details about the show.
It's usually sufficient to help you decide which show is the one you want.     
For example, looking between the two shows, the one in the first image below is an Italian show, and the one in the second image is from CBS in the USA.
![image](https://user-images.githubusercontent.com/6933240/31833442-0f1490ee-b627-11e7-9981-08cb936f7752.png)
![image](https://user-images.githubusercontent.com/6933240/31833535-53484724-b627-11e7-9bb0-1046255e9b7e.png)
But if you cant tell them apart, you could also check out the Trailer video for each to show by clicking on the video icon on the poster, or the watch-trailer on the side-panel.
![image](https://user-images.githubusercontent.com/6933240/31833745-ffc06c70-b627-11e7-916d-07f38d44d9e6.png)
![image](https://user-images.githubusercontent.com/6933240/31833810-2f9f9cae-b628-11e7-9e26-e5c855127b70.png)
But even if you do pick the wrong show, once it has been added, you can always visit that show's details side-panel and click on the remove-from-favourites to delete it from DuckieTV.
![image](https://user-images.githubusercontent.com/6933240/31833910-934f1b44-b628-11e7-95bb-5446c489f758.png)

Finally, try out the latest Nightly beginning with the 20-10-2017 11:09:08 release, it contains a fixed downloaded-watched decoupling, so if you set that flag in the *Settings,Misc* side-panel to **disabled**, then when you mark an episode as watched it will not also set it to downloaded, which should help you avoid seeing the green highlights that you seem to dislike so much ;-)
![image](https://user-images.githubusercontent.com/6933240/31834120-759233ba-b629-11e7-80a1-01c97fa54912.png)

**Closed as completed by garfield69** 2017-10-20 17:36 UTC
Labels: Help Wanted
