### ISSUE TITLE
MAC Standalone 1.1.2 all the WEB Torrent Integration settings side-panels are empty

### ISSUE THREAD

**Issue by jalinbank** [SchizoDuckie/DuckieTV#513] opened 2015-07-25 01:52 UTC
The side panel for the standalone version is blank for transmission settings. 
![screen shot 2015-07-25 at 11 46 04 am](https://cloud.githubusercontent.com/assets/10136596/8887392/f00527b6-32c2-11e5-89d3-e1ea4a6bf2cd.png)

Checked on Chrome New-Tab and Action-Button version and settings panel is visible.
![screen shot 2015-07-25 at 11 49 38 am](https://cloud.githubusercontent.com/assets/10136596/8887395/49c56d88-32c3-11e5-84cd-6bdf37c9f52b.png)

**Comment by garfield69** [comment] 2015-07-25 02:26
Please confirm the version of the standalone you are using, by checking the ABOUT page (i) icon on bottom left of main DuckieTV page. Also, let us know which platform OS you are running it under.
Thanks.

**Comment by brandbrilliance** [comment] 2015-07-25 12:00
I've got Mac Version 1.1.2 and my screen is also blank. It did say to restart Duckie after changing the torrent provider.

**Comment by jalinbank** [comment] 2015-07-25 12:48
Its the Mac version 1.1.2. Probably easier to upload the statistics section:
![screen shot 2015-07-25 at 10 45 11 pm](https://cloud.githubusercontent.com/assets/10136596/8889477/16e295e2-331f-11e5-8fb8-f962b6d65888.png)

I've also noticed the duckie logo appears multiple times in the toolbar at the top of the screen.

**Comment by garfield69** [comment] 2015-07-25 20:08
Ah, interesting. 
- Re: multiple ducklings icons...
The multiple ducklings at the top might be an indication that DuckieTV may not be shutting down properly on the mac when you press the X, leaving a stub behind. Each subsequent restart could add to the task list. Do you have some way of checking the task manager to see if there are indeed  multiple DuckieTV ?
Alternatively, if you were to shut-down and restart the mac afresh, and then start DuckieTV, is there just the one icon now?
- Re: Transmission side panel empty.
It would be useful to know if it is only the Transmission client side panel that is empty on the mac, or if all the others (with the possible exception of uTorrent) are empty as well?
BTW, thank you for your feed back.

**Comment by lonelyfairie** [comment] 2015-07-25 21:19
On MAC client all torrent settings appear blank, integration works if you use default settings (e.g. uTorrent web ui left with password blank and username admin) but you cannot change any settings. I did post a screenshot to the facebook page and was told a new release was coming shortly that would fix it (that was about a week ago).

**Comment by jalinbank** [comment] 2015-07-26 13:14
* The ducks seem to appear one-by-one when DuckieTV is left open/minimised. Another one pops up every ~30 minutes. When the window/program is closed properly (X), all the ducks disappear, and re-opening the app returns only one duck to the toolbar (and then the other ducks follow). Looking at the Activity Monitor, it only shows one instance of DuckieTV running. I also noticed when I press "Reload DuckieTV to use [torrent client]" is adds 4-6 more ducks to the toolbar each time.

* The side panel is blank for:
  * Deluge
  * Tixati
  * Vuze (shows "click here for setup instructions" but nothing below that)
  * qBittorrent
  * qBittorrent V3.2+ (has a small orange square below the logo, but nothing else)
  * uTorrent Web UI (shows the picture for pimp my uTorrent, but nothing else)

**Comment by garfield69** [comment] 2015-08-06 00:02
re: ducklings. Schizoduckie has re-factored the standalone start-up as part of another issue, and believes he has also corrected this problem on the Mac at the same time. Of course we wont know for sure, until this release gets pushed out into the wild. No ETA as yet, plenty of other stuff still pending.

**Comment by lonelyfairie** [comment] 2015-08-27 13:35
Any ETA on this? Sorry to bug so much but currently I am unable to use couchpotato for my movies since that is not allowing Utorrent UI without a password, and since I prioritize my daily series and DuckieTV is not allowing to set a password I am currently unable to use both at the same time.
I don't wanna give up my movie automatization over this :cry:

**Comment by yourboyvic** [comment] 2015-08-28 15:52
![screen shot 2015-08-28 at 8 41 37 am](https://cloud.githubusercontent.com/assets/6733145/9550674/912c3b58-4d61-11e5-8603-7bf1c2217d36.png)

I'm also having this problem with qbittorrent

![screen shot 2015-08-28 at 8 49 08 am](https://cloud.githubusercontent.com/assets/6733145/9550730/e3170c68-4d61-11e5-8085-4021f93fd6db.png)

I have duckietv 1.1.2

![screen shot 2015-08-28 at 8 49 00 am](https://cloud.githubusercontent.com/assets/6733145/9550734/e798ab66-4d61-11e5-9bd7-4eecc01c839d.png)

I'm on mac os x 10.10.5

![screen shot 2015-08-28 at 8 50 30 am](https://cloud.githubusercontent.com/assets/6733145/9550736/e9ffba3e-4d61-11e5-9ff0-538a0fc8dbcd.png)

qbittorrent 3.2 integration works in chrome but not in standalone

**Comment by SchizoDuckie** [comment] 2015-08-28 15:55
Sorry guys, i'll look into this shortly but my mac vm doesn't want to boot
anymore so I cannot verify anything :-/

**Comment by lonelyfairie** [comment] 2015-08-28 15:55
Vic, as the title of the issue says it is not specific to one torrent client unfortunately :(
The only workaround so far is to use the default settings for the client you are using, e.g the default username and password and port.

Thanks Schizo Duckie! If you need help testing let me know I will be glad to do so...

**Comment by SchizoDuckie** [comment] 2015-08-28 15:57
If you are really curius and cannot wait, you can always just download the
.zip file from the repository, and download nw.js for mac. Extract the
nw.js files tot he angular folder and then run it. That should give you the
latest and greatest DuckieTV standalone for mac

**Comment by yourboyvic** [comment] 2015-08-28 22:14
Oh man, this response is great.

I will return my qbittorrent to the default settings first. I will look
into node webkit second.

schizo your app, plug-in and hard word are amazing.

Thank you for your efforts, attention to your audience/community and
continued development.

YBV



Victor K.
415-577-7339

My cars for sale <http://sfbay.craigslist.org/search/sss?userid=222176749>

Write a DEALER RATER review for me
<https://www.dealerrater.com/dealer/add-review.aspx?dealerId=17013>!

OR, if you're a YELPER

<http://vic.kim/link/yelpreview>
Write a YELP review for me! <http://vic.kim/link/yelpreview>

**Comment by lonelyfairie** [comment] 2015-09-19 01:03
Man... I spent like 2 weeks trying to install Angular and following like a million tutorials to install needed tools like ruby and node on my mac and not finding a way to just run an angular app directly just to come back all frustrated to ask for further instructions and re read your comment and finding that the instructions where there from the start... *facepalm* 

I am happy to report that I am now running DuckieTV using node and have full control of the torrent settings... you are pure magic SchizoDuckie! If you ever need a Mac tester I am more than available :)

**Comment by lonelyfairie** [comment] 2015-09-28 14:37
I am using the latest angular version available and I am still seeing the multiple ducks whenever you minimize the app instead of closing it, is there another issue open for this?

**Comment by SchizoDuckie** [comment] 2015-09-28 20:00
Thanks for the reminder @lonelyfairie. I've just finally finished fixing my mac VM and the nightly build system and will look into that right away!

**Comment by lonelyfairie** [comment] 2015-10-01 15:59
Thanks SchizoDuckie, let me know if you want me to open a new issue to track it or test any new builds.

**Comment by lonelyfairie** [comment] 2015-10-03 01:09
Just downloaded the latest commit, no more multiple duckies and no duckies at all in the system tray. Is this the expected behaviour?

**Comment by SchizoDuckie** [comment] 2015-10-03 01:12
There should appear a duckie when you minimize duckietv!

**Comment by lonelyfairie** [comment] 2015-10-03 02:52
Sorry SchizoDuckie... no duckie on my mac :(
![screen shot 2015-10-02 at 23 50 13](https://cloud.githubusercontent.com/assets/13501166/10261161/6c2c14c0-6960-11e5-8054-69f30123d439.png)
![screen shot 2015-10-02 at 23 51 28](https://cloud.githubusercontent.com/assets/13501166/10261165/8df971d8-6960-11e5-9a21-2e514f04b976.png)

**Comment by garfield69** [comment] 2015-10-03 03:08
@lonelyfairie  We've changed the minimized code to offer users the choose to minimize to the Taskbar or Systray. This change removed the previous minimize-to-systray setting.

 So if you are wanting to minimize on startup to the Systray then please check that the following settings on the display panel are: 'window on startup' = minimized, and 'minimize location' = systray
![image](https://cloud.githubusercontent.com/assets/6933240/10261198/805180d8-69e8-11e5-8dbc-ab8b676ba117.png)

Please confirm the settings, and let us know the result. Thanks.

**Comment by lonelyfairie** [comment] 2015-10-03 04:41
Hi Garfield, I didn't know of the settings add, I had the settings on Minimize to Taskbar so when you have it like that it makes sense that no duckie is shown.
I changed the setting to use the Systray and when I minimize I get two duckies, it is not cumulative like before that every time you minimized it would add a duckie, now when you minimize you get two duckies, when you maximize the duckies go away, minimize again and you still get two duckies.
Screenshot attached.
![screen shot 2015-10-03 at 01 37 32](https://cloud.githubusercontent.com/assets/13501166/10261470/e9c69ba8-696f-11e5-8687-31e452a95e4c.png)

**Comment by garfield69** [comment] 2015-10-03 04:48
reopened in light of the latest mac testing.

**Comment by garfield69** [comment] 2015-10-03 04:49
@lonelyfairie  do both systray icons respond to the maximise click, or just one or the other?

**Comment by garfield69** [comment] 2015-10-03 05:02
@SchizoDuckie 
looks like 
```javascript
var clickie = new gui.MenuItem({ label: 'Show DuckieTV' });
```
results in two tray icons being created on the mac.
[nwjs menu doc](https://github.com/nwjs/nw.js/wiki/Menu) has this example for adding menu items
```javascript
// Create an empty menu
var menu = new gui.Menu();
// Add some items
menu.append(new gui.MenuItem({ label: 'Item A' }));
```
I'd make the change myself but since I don't have a mac (or emulator) I've no way of pre-testing before release, so I rather not make a change when I cant even confirm it does not cause a crash ;-)

**Comment by Js41637** [comment] 2015-10-03 06:11
Looks like it's time to light the beacon. http://www.js41637.com/duckiepls/
![image](https://cloud.githubusercontent.com/assets/6258213/10261737/55c36ba0-69e9-11e5-880d-ab85020af34a.png)

**Comment by SchizoDuckie** [comment] 2015-10-03 08:45
Hmm. this worked on my mavericks vm. I will do some more verification and
testing. Thanks for checking up on it @lonelyfairie !

By the way I do think we should make the new minimize to taskbar feature
not the default to not break backwards compatibility.

**Comment by lonelyfairie** [comment] 2015-10-03 17:32
I forgot to mention I am running El Capitan on my mac.

Date: Sat, 3 Oct 2015 01:45:27 -0700

**Comment by lonelyfairie** [comment] 2015-10-03 17:34
Both icons appear and disappear at the same time, it is not like before that duckies would appear each time you minimized but that instead of one icon I get two no matter the action.

Date: Fri, 2 Oct 2015 21:49:52 -0700

**Comment by lonelyfairie** [comment] 2015-10-05 15:04
![screen shot 2015-10-05 at 12 02 07](https://cloud.githubusercontent.com/assets/13501166/10284183/11184946-6b59-11e5-93e9-5c1374f566f1.png)

Fixed with latest angular version, thanks guys :+1: 
Unrelated, any chance I can get some duckietv car stickers sent to Argentina? lol

**Comment by SchizoDuckie** [comment] 2015-10-05 18:27
@lonelyfairie does this mean that you fully re-tested and no longer see duplicated duckies?

I'm preparing the stickers tonight, so if you shoot me an address via email and some preferences I will make sure you're in the batch!

**Comment by lonelyfairie** [comment] 2015-10-05 19:01
SchizoDuckie, yeap, I updated to the latest angular version this morning and re tested an as you can see only one duckie shows when minimized :)
What's your email to send you my address?

**Comment by SchizoDuckie** [comment] 2015-10-05 19:02
Excellent. Will close this issue then. 

You can reach me at tvduckie@gmail.com :)

**Closed** 2015-10-05 19:13 UTC
Labels: 3 - Done, bug
