### ISSUE TITLE
StandAlone 0.92 SceneNameResolver cannot reference moment

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#346] opened 2015-01-29 08:41 UTC
as per log below.
![image](https://cloud.githubusercontent.com/assets/6933240/5954681/7717ad40-a7ff-11e4-8124-789c2dfe2314.png)

**Comment by SchizoDuckie** [comment] 2015-01-29 08:43
This should be fixed with 0.92 (release not complete yet, uploading took too long before i had to get to work)

**Comment by SchizoDuckie** [comment] 2015-01-29 08:44
https://github.com/SchizoDuckie/DuckieTV/releases/tag/0.92

**Comment by garfield69** [comment] 2015-01-29 16:07
Sorry no. I used the Standalone 0.92 windows package from https://github.com/SchizoDuckie/DuckieTV/releases/tag/0.92

Chrome Browser works fine. Problem is specific to Standalone. 

May be a reference within SceneNameResolver is needed to satisfy StandAlone stricter control?

**Comment by SchizoDuckie** [comment] 2015-01-29 22:23
The problem is that moment detects that requirejs is available in the node-webkit environment, it will not register itself then with a global variable. Thanks for the research!

**Closed** 2015-01-29 22:24 UTC
Labels: 1 - Ready, bug
