### ISSUE TITLE
Alternate torrent search name for specific show(s)

### ISSUE THREAD

**Issue by shadycady** [SchizoDuckie/DuckieTV#476] opened 2015-06-26 07:14 UTC
Alternate torrent search for specific show(s)

For example:
Rizzoli & Isles = Rizzoli and Isles
20/20 = 2020
no torrents found = torrents found
I'm sure this happens for many tv show names. Rare but if you look surely there are a more.
It just hinders auto downloading as looking for torrent and changing as above solves issue.

instead of using title of series as it does, can it be modified and keep season and episode info as is? 
as a series option? 
or I guess a list could be made of show names and changed (might take some time)

Set up for my Mom to watch a few shows and keep up.
Damn parents have to watch their 20/20, damn if I don't help my parents but they are real bug finders...
couldn't code or even install a piece of software but damn if they aren't good testers, well good at breaking code.

Love this program

**Comment by garfield69** [comment] 2015-06-26 08:51
>Rizzoli & Isles = Rizzoli and Isles

Actually the the `&` and `and` are interchangeable in the torrent search results and will not cause issues. example below
![image](https://cloud.githubusercontent.com/assets/6933240/8373704/42c949a0-1c43-11e5-9cbe-3746945f1092.png)
 >20/20 = 2020

20/20 however is a candidate for our SceneNameResolver. Actually qualifies twice ;-)
Once to change 20/20 to 2020, and again to switch from SxxExx to YYYY MM DD date string replacement.
So I will add this to the module and it will go out with the next DuckieTV release.

The SceneNameResolver module is the best method we have found so far to help deal with show name anomalies and season/episode versus release-date variations.

>instead of using title of series as it does, can it be modified and keep season and episode info as is? as a series option? 

I will defer to @SchizoDuckie to answer this one. :-)

**Comment by shadycady** [comment] 2015-06-26 10:55
So in the future would I post another show if found where I did?

I was only trying Kickass which for Rizzoli & Isles it just keeps searching
works for the rest.

Thanks for the quick reply.

PS
is there a way to open minimized to tray as I have it in startup folder.
There is no options as to start up with windows in the program correct?

**Comment by garfield69** [comment] 2015-06-26 16:50
>So in the future would I post another show if found where I did?

Yes :-)

>I was only trying Kickass which for Rizzoli & Isles it just keeps searching.

Hmm. Should work on KickAss too. Please check the ABOUT page statistics (click on the (i) icon on the action bar on the left side of the DuckieTV page) and check that your `Torrenting Search Provider` is KickAss and that the `Torrenting URL` is set to https://kat.cr
![image](https://cloud.githubusercontent.com/assets/6933240/8382328/1acb7fca-1c86-11e5-8968-e27f3c6b9b17.png)
If it is set correctly then perhaps the KickAss' web search engine was overloaded or busy or something.

>is there a way to open minimized to tray as I have it in startup folder. There is no options as to start up with windows in the program correct?

Correct. But I think that is a great idea, so I will add an option in settings to start the Standalone minimized and if Schizoduckie likes it, it will be included in the next release of DuckieTV.

**Comment by SchizoDuckie** [comment] 2015-06-26 17:08
> Correct. But I think that is a great idea, so I will add an option in settings to start the Standalone minimized and if Schizoduckie likes it, it will be included in the next release of DuckieTV.
Sounds like a great idea indeed!

In response to your ticket: we're already preparing for custom search strings per show for the next release, and might as well add custom TorrentSearchEngine as well, but this will flesh out in future releases. I've also been thinking about creating a fallback flow, so that if for instance KAT finds 0 results and TPB does, you'll get the TPB result.

**Comment by shadycady** [comment] 2015-06-27 01:37
I tried KAT a few times with & in title.  KAT doesn't seem to like the &
symbol, it just keeps searching.

I think you guys are doing an awesome job with this program!  I think
fallback flow will be a great feature add!

Would it be hard to add a button to open/play episode from DuckieTV.  I get
the question from new people I introduce to this software that have a hard
time navigating.  Maybe it could open similar to hitting play from
uTorrent? ... and as such maybe the program would mark episode as watched.

When I click on the episode from calendar it opens the side screen.  In the
box marked TORRENT, it has start, pause and stop.
When I click on show files it does not list them as something select-able
but if it did, I would assume that double clicking video file it could be
opened in my default media player? Doesn't have to be there, maybe in
episode listings... not sure where the best placement would be?

Thank you for responding to my previous comments.

I have had a computer hooked to my tv for many years, before 'smart'TV. I
don't think I have used one 'smart' feature on my TV.  I also have TV
tuners which just sits there now as getting my programming more often at
higher res and lower size from DuckieTV.

Thank you so much for the great program and experience it brings.

On Fri, Jun 26, 2015 at 10:08 AM, SchizoDuckie <notifications@github.com>
wrote:

> Correct. But I think that is a great idea, so I will add an option in
> settings to start the Standalone minimized and if Schizoduckie likes it, it
> will be included in the next release of DuckieTV.
> Sounds like a great idea indeed!
>
> In response to your ticket: we're already preparing for custom search
> strings per show for the next release, and might as well add custom
> TorrentSearchEngine as well, but this will flesh out in future releases.
> I've also been thinking about creating a fallback flow, so that if for
> instance KAT finds 0 results and TPB does, you'll get the TPB result.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SchizoDuckie/DuckieTV/issues/476#issuecomment-115768992>
> .
>



-- 
Travis Cady
Carpe Diem, Quam minimum credula postero

**Comment by garfield69** [comment] 2015-06-27 02:02
>I tried KAT a few times with & in title.  KAT doesn't seem to like the & symbol, it just keeps searching.

I presume you have confirmed that you are using `https://kat.cr` as the torrenting url, like I asked to to check earlier.
If this is the case, then after your search fails to work, press `F12` and go to the `console` tab and post a screen dump here of any error messages you see. There may be an error in the log that could explain why the search is failing for you, because it should otherwise be working.

as for the rest, I defer to schizoduckie for an answer.

**Comment by garfield69** [comment] 2015-06-27 02:07
@scizoduckie, my testing of the standalone start-up-minimized has dredged up an bonus 'feature' ;-)
if you have the setting set to minimize on start-up, then when you later select any other settings option that calls `window.location.reload();` (like when setting languages), then the window gets auto-minimized!
Is anything we can do about this?

**Comment by shadycady** [comment] 2015-06-27 02:12
I'm sorry I just quickly scanned and emailed you back. Wasn't home at the
time. You are correct if set to kat.cr
Fixed problem.

It had another proxy which I had not noticed when I was messing with
options.

**Comment by shadycady** [comment] 2015-06-27 02:40
With KAT unlike the rest if say you put in Defiance S03E04 it comes up with
a long list but no S03E04 as it hasn't been uploaded. The rest of the
torrent search engines come up blank / no search results. So if you set
default to KAT it will download what it finds at the top of the list when
it checks.

You can test by putting in any show episode that hasn't been aired. However
if you put in a episode that has been released it only come up with exact
episodes available.

I hope I am not wearing out my welcome.
I appreciate all your work and help!

Tried to send you a few pics but email failed due to size.

**Comment by garfield69** [comment] 2015-06-27 02:54
>With KAT unlike the rest if say you put in Defiance S03E04 it comes up with
a long list but no S03E04 as it hasn't been uploaded. The rest of the
torrent search engines come up blank / no search results. So if you set
default to KAT it will download what it finds at the top of the list when
it checks.

Yeah, that's a 'feature' of KAT that gives DuckieTV's auto-download function fits. Ticket #396 was raised for this previously.

>I hope I am not wearing out my welcome.

Nah, constructive suggestions and bug reports are always welcome. :smile:

**Comment by SchizoDuckie** [comment] 2015-06-27 09:16
> Would it be hard to add a button to open/play episode from DuckieTV.

For the standalone version that wouldnt be too hard now anymore now that we have the proper files listing per torrent. I Could just launch it on the default system player. However, I would like to create a generic method so that it can also launch videos to for instance Video Stream for Chrome. We should probably flesh this out in a new ticket

**Closed** 2015-07-03 20:26 UTC
Labels: 3 - Done, enhancement, Help Wanted, question, Testing Completed, translations - done

**Comment by shadycady** [comment] 2015-07-06 00:03
I finally found time to try to download the newer version but when I click
on the windows badge to download nothing happens.


On Fri, Jul 3, 2015 at 1:26 PM, garfield69 <notifications@github.com> wrote:

> Closed #476 <https://github.com/SchizoDuckie/DuckieTV/issues/476>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SchizoDuckie/DuckieTV/issues/476#event-347609737>.
>



-- 
Travis Cady
Carpe Diem, Quam minimum credula postero

**Comment by garfield69** [comment] 2015-07-06 01:27
>I finally found time to try to download the newer version but when I click
on the windows badge to download nothing happens.

@shadycady  that's because Schizoduckie has not published the standalone binaries yet ;-)
He had a glitch with the chrome store push, and it has thrown his schedule out of kilter.
I don't have an ETA for you at this stage sorry.

**Comment by shadycady** [comment] 2015-07-30 07:46
Is there anyway to remedy shows like for instance -

American Pickers -  it searches for s2015e# rather than s07e#

The Next Food Network Star S11E07 doesn't work but Food Network Star S11E07
comes up with torrents (this one I don't quite get?)

Those 2 are the ones that fail out of 25 - 30 shows every week

If there was a option to modify how the search string is put together
before used to search.

Don't get me wrong those are small problems i'm sure compared to keeping
this thing so automated.
Just a friendly question.

As a whole have given a bunch of my friends this and these are a few of
errrors that keep happening

And everybody says one thing either how do I get that or I love this Thanks



On Sun, Jul 5, 2015 at 6:27 PM, garfield69 <notifications@github.com> wrote:

> I finally found time to try to download the newer version but when I click
> on the windows badge to download nothing happens.
>
> @shadycady <https://github.com/shadycady> that's because Schizoduckie has
> not published the standalone binaries yet ;-)
> He had a glitch with the chrome store push, and it has thrown his schedule
> out of kilter.
> I don't have an ETA for you at this stage sorry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SchizoDuckie/DuckieTV/issues/476#issuecomment-118687449>
> .
>



-- 
Travis Cady
Carpe Diem, Quam minimum credula postero

**Comment by garfield69** [comment] 2015-07-30 09:56
>Is there anyway to remedy shows like for instance -
>American Pickers -  it searches for s2015e# rather than s07e#

Not currently. This is because on Trakt.TV's database the numbering for this particular show's episodes is s2015e#, but the torrent up-loaders are using s07e# for their torrent names.
DuckieTV has no way to resolve s07e# out of the information it gets from Trakt.TV

>The Next Food Network Star S11E07 doesn't work but Food Network Star S11E07
>comes up with torrents (this one I don't quite get?)

Once again a discrepancy between what Trakt.TV names a series, and what the torrent up-loaders name the torrents of that series. So on Trakt.TV its THE NEXT FOOD NETWORK STAR but the torrent up-loaders are naming the show as just FOOD NETWORK STAR.

However, this one we can fix, I'll amend our sceneNameResolver to return the short name. It will be included in the next release of DuckieTV.

**Comment by garfield69** [comment] 2015-07-30 21:26
good news. Schizoduckie has just found this:

Xross Entity Map

The Xross Entity Map for TV shows
xem helps you keep an overview of your shows on different websites.
Many websites use different numberings, names and season titles for the same show.
xem lets you create a map for an easy overview of all the different counting and naming systems.

Example API call
http://thexem.de/map/single?id=141181&origin=tvdb&season=2015&episode=2&destination=scene

so we will look at integrating this into DuckieTV and perhaps this will resolve the American Pickers issue amongst others.

**Comment by shadycady** [comment] 2015-08-05 04:18
I have a question, about how duckieTV checks for new episodes.  I tried
lowering the seed required. But I wonder what triggers the download of an
episode as sometimes when I am wanting for todays episode for a specific
show sometimes I find the torrent with 100s of seeds but the program
doesn't trigger the show to download.  I guess I am asking about if there
is an interval that it checks by?  I leave this program running all the
time in the background. Just set to run at startup.If I shutdown and reopen
it will usually trigger after restart up.
I'd love to be able to set it to check a few times an hour if possible as I
love how close it is to total automation.
Its a request but maybe would complicate something else..... Always want
something else /more... how come they can't just give me the whole season
;-) I hate waiting, tell me what happens next!

Anyways love the program. Thanks for any incite.

I took a few basic programming classes so I'm sure I could dig into the
program and maybe answer or test some of the things I ask.
Could you recommend an editor or/and any tools to get started as a
beginner.  Or any helpful hints as to where to start. I'm sure I'm rusty as
a coder since it has been years since I wrote anything.

Thanks Travis

On Thu, Jul 30, 2015 at 2:26 PM, garfield69 <notifications@github.com>
wrote:

> good news. Schizoduckie has just found this:
>
> Xross Entity Map
>
> The Xross Entity Map for TV shows
> xem helps you keep an overview of your shows on different websites.
> Many websites use different numberings, names and season titles for the
> same show.
> xem lets you create a map for an easy overview of all the different
> counting and naming systems.
>
> Example API call
>
> http://thexem.de/map/single?id=141181&origin=tvdb&season=2015&episode=2&destination=scene
>
> so we will look at integrating this into DuckieTV and perhaps this will
> resolve the American Pickers issue amongst others.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SchizoDuckie/DuckieTV/issues/476#issuecomment-126495376>
> .
>



-- 
Travis Cady
Carpe Diem, Quam minimum credula postero

**Comment by Js41637** [comment] 2015-08-05 04:26
Yeah it's on a timer I think and we were meant to get around to making it configurable

**Comment by shadycady** [comment] 2015-08-05 04:30
Once the torrent completes are you supposed to be able to play the file
from clicking on episode in calendar and clicking show files. It has always
just shown 5 dots / blank.

**Comment by Js41637** [comment] 2015-08-05 04:31
Yeah the Show Files is currently broken, it has since been fixed though and will be in next release.

As for editors, I use Sublime Text 2 and I think SchizoDuckie uses Sublime Text 3.

**Comment by shadycady** [comment] 2015-08-05 04:37
So I can pull latest code from github?
Then can I use sublime to compile, I think just for Windows standalone.
Never wrote anything a mac liked ;-)
I apologize for such noob questions.
I greatly appreciate the point in the right direction.

**Comment by Js41637** [comment] 2015-08-05 04:54
No Sublime doesn't compile, the code on Github can be run as-is as a Chrome Extension however for Standalone, I don't really know anything about how it works or gets compiled. I think the files here can be just copied over to the standalone folder and then run the standalone and it should work. I don't have a copy of standalone atm to test. But before you do anything best to backup.

**Comment by garfield69** [comment] 2015-08-05 05:15
To run a development DuckieTV standalone pack you need to:
Grab the DuckieTV GitHub zip package and unpack it to a dedicated directory.
Then grab the latest nwjs package, currently 0.12.3 from http://dl.nwjs.io/v0.12.3/ 
I use the nwjs-v0.12.3-win-ia32.zip because I run a windows 32bit system.
Unpack that and copy the content of the main directory to the DuckieTV directory you set up previously.
You can disregards the locale directory that came with the package, DuckieTV has its own locale stuff.
Then run nw.exe and you are away.

**Comment by garfield69** [comment] 2015-08-05 08:10
BTW, by default, both the production and development standalone startups are going to point to the same database location. 
So if you want to keep your development standalone DuckieTV database separate you need to change your developments package.json to point to a new location. 
change line 107 
`  "name": "DuckieTV-Standalone",` to `  "name": "DuckieTV-Standalone-dev",` for example.
