### ISSUE TITLE
auto download stoped working

### ISSUE THREAD

**Issue by ofirshtrull** [SchizoDuckie/DuckieTV#1069] opened 2018-03-29 14:42 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
... Standlone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Stable 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
... win 10

**Describe the problem you are having and steps to reproduce if available**
...auto download stop working i have BitTorrent working but since one of the updates it shows "no activaty, utorrent offline.  and nothing has changed in the configurations of ducky or the torrent client

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2018-03-29 19:01
Duplicate of #1048
As you may know, BitTorrent and uTorrent share the same source code. I presume you are using BitTorrent 7.10.3 (44359) which I think is the latest windows version.

Recently, the uTorrent/BitTorrent team upgraded their apps security, which resulted in breaking the default DuckieTV uTorrent/BitTorrent API integration.

However, you can still connect to the latest BitTorrent by using the DuckieTV uTorrent WEBUI.
Read this wiki for set up details https://github.com/SchizoDuckie/DuckieTV/wiki/Setting-up-uTorrent-Web-UI-with-DuckieTV

**Closed as completed by garfield69** 2018-03-29 19:01 UTC
Labels: duplicate
