### ISSUE TITLE
S.W.A.T.TV show not searching correctly

### ISSUE THREAD

**Issue by TwitchKappa** [SchizoDuckie/DuckieTV#991] opened 2017-11-04 19:08 UTC
when the new TV show S.W.A.T. is added to the program it searches for it without periods in the name which produces incorrect results. as a result the show cannot be automatically downloaded and searches have to be done manually. Please fix this thank you

https://trakt.tv/shows/s-w-a-t-2017

**Comment by garfield69** [comment] 2017-11-04 19:24
duplicate of #990 
Your DuckieTV should fetch the updated sceneNameException table from our servers within the next 24 hours and start using the corrected name.

**Closed as completed by garfield69** 2017-11-04 19:24 UTC
Labels: duplicate
