### ISSUE TITLE
Still can't connect with qbittorrent v4.0.2

### ISSUE THREAD

**Issue by spmilden** [SchizoDuckie/DuckieTV#1026] opened 2018-01-20 19:32 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly V201801140130

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...Sorry to bug you again. I uninstalled v4.0.3 and installed v4.0.2 but still can't connect. 

**Attach any DuckieTV statistics or Developer Console logs if available**
...Failed to load resource: the server responded with a status of 400 (ERROR)
app.js:3724 qBittorrent 3.2+ connect error! Object
(anonymous) @ app.js:3724
spmilden:*******@localhost:8080/version/api Failed to load resource: net::ERR_CONNECTION_REFUSED
deps.js:2354 qBittorrent 3.2+ Connect call failed.
(anonymous) @ deps.js:2354
app.js:3724 qBittorrent 3.2+ connect error! qBittorrent 3.2+ Connect call failed.
(anonymous) @ app.js:3724

**Comment by garfield69** [comment] 2018-01-20 19:37
show me a screen capture of your qBt webui settings page.
and one of your duckietv qBt 3.2+ integration page.

**Comment by 2635599** [comment] 2018-01-20 20:37
is it not connecting or does dtv simply state it can't connect? i left qbittrrent 4.0.3 installed cause regardless of the message in dtv it does pass the torrent info to qbt, and qbt downloads the torrent just fine.

**Comment by spmilden** [comment] 2018-01-20 21:05
![qbt](https://user-images.githubusercontent.com/35412880/35187959-79c2df4c-fdfb-11e7-863d-81d6492f42d5.jpg)
![dtv](https://user-images.githubusercontent.com/35412880/35187972-9fd194bc-fdfb-11e7-8a6f-030364c29f28.jpg)

**Comment by garfield69** [comment] 2018-01-20 21:59
if you use your chrome browser to access the qBt webui, by pasting `http://localhost:8080` in the address box, do you get the qBt login challenge and can you then login to it?

**Comment by spmilden** [comment] 2018-01-21 00:45
It returns Invalid Request

**Comment by garfield69** [comment] 2018-01-21 01:00
maybe something has grabbed port 8080 but has not released it for qBt to use (the old utorrent?).      
so on qBt's webui setting page, set the port to 8085 and save it, then shut down qBt and duckietv.
start qBt, then duckietv, then on duckietv's qBt integration page set the port to 8085 and see if you can make that work.

**Comment by spmilden** [comment] 2018-01-21 01:21
That makes sense as utorrent was set to port 8080 and I haven't uninstalled it yet.
Before I do, quick question - using qbittorrent if I set the download path in DuckieTV is the torrent downloaded to the specified folder or moved after it completes? Thanks again for your help.

**Comment by garfield69** [comment] 2018-01-21 01:33
> if I set the download path in DuckieTV is the torrent downloaded to the specified folder or moved after it completes?

I believe the torrent downloaded to the specified folder.
if you are looking for post-processing of files after a download to a common folder, then I can recommend a filemanger like FileBot. see this [wiki](https://github.com/SchizoDuckie/DuckieTV/wiki/Pairing-DuckieTV-with-FileBot-for-a-fully-automated-media-center) for examples.

**Comment by crashwave** [comment] 2018-01-26 00:59
QBT was working fine with DTV for a long time up until a little over month ago. changed modem and set network from public (not sure why it was set to that) to private and after that nothing. Changed network back to public nothing. Uninstalled both dtv and qbt several time still not connecting.
Standalone Duckietv on 64 bit windows 10, Comodo internet sec. 
Here is the error I get. Not sure if chrome, any help appreciated 

Error: {"data":"","status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"headers":{"Content-Type":"application/x-www-form-urlencoded","X-Forwarded-Host":"chrome-extension://bagblfnohpiddokbpaacecffdboomafe","Accept":"application/json, text/plain, */*"},"url":"http://localhost:8080/login","data":"username=admin&password=*****"},"statusText":"Unauthorized"}

**Comment by garfield69** [comment] 2018-01-26 01:03
@crashwave  Yes, qBt made a change in 4.0.3 that broke the DuckieTV qBt client interface. qbittorrent/qBittorrent@b827761 fixes this problem, which will be included in the next qBt release, whenever that gets published.
The problem cannot be fixed by DuckieTV, so 4.0.2 is the current compatible client.

**Comment by garfield69** [comment] 2018-01-27 00:04
@spmilden  so did you succeed in connecting qBt 4.0.2 with DTV once you switched ports?

**Comment by spmilden** [comment] 2018-01-28 02:31
@garfield69 I did but the downloads still went to the default drive and folder rather than to the path specified. It's a bit of a pain to manually move the finished downloads to the proper folders so Plex can recognize the shows and download the metadata for them but it's not a huge deal. I'll have some time to play around with other clients in a few days. If I figure it out I'll let you know. Thanks for following up!

**Closed as completed** 2018-01-28 02:36 UTC
Labels: Help Wanted

**Comment by garfield69** [comment] 2018-01-28 03:19
Just tested qBt 4.0.2 with my DTV set with series dlpath.
In order to make qBt use the path provided by DTV, you first must set your qBt download settings to *manual*.
![image](https://user-images.githubusercontent.com/6933240/35478619-f514aa12-0446-11e8-9461-1398bc62e373.png)
otherwise qBt will continue to use it's default download path ;-)

**Comment by spmilden** [comment] 2018-01-29 01:04
Thanks - I'll give it a shot and let you know.

**Comment by spmilden** [comment] 2018-01-29 18:10
Still downloading to the default path. I'm pretty sure I have the settings correct. Am I missing something else
![dtv-1](https://user-images.githubusercontent.com/35412880/35526512-a404b18a-04f5-11e8-867a-cb8af71f2bbf.jpg)
?
![qbt settings-1](https://user-images.githubusercontent.com/35412880/35526472-89e8e4ec-04f5-11e8-9238-21d44d8c0968.jpg)
![qbt settings-2](https://user-images.githubusercontent.com/35412880/35526492-94f952ae-04f5-11e8-9e63-0dbe9ad0edee.jpg)

**Comment by garfield69** [comment] 2018-01-29 19:47
did you recycle qBt and DuckieTV after making all those settings changes?
After which only new torrents started from DTV will get the path set (assuming you saved the dlpath for the associated DTV series), any existing torrents on qBt are not touched.
Can I see a shot of a DTV series that has the dlpath set, and a shot of the related qBt torrent *General* tab with the Save Path?
Also you can turn on qBt logging and check the log for errors after you start a DL from DTV.
![image](https://user-images.githubusercontent.com/6933240/35530806-0052d2a6-059a-11e8-8bc4-14553d4dc6a0.png)

**Comment by spmilden** [comment] 2018-01-30 02:59
Yes I had reset both and no errors.
![dtv settings](https://user-images.githubusercontent.com/35412880/35545860-3dffb41c-053f-11e8-9d65-74f625c0089e.jpg)
![qbt general](https://user-images.githubusercontent.com/35412880/35545861-3e400878-053f-11e8-80f0-770b2b11fc51.jpg)

**Comment by garfield69** [comment] 2018-01-30 03:16
Hmm. take a look at the DTV logs (press **F12** to open the *Development Tools* page, and click on the **Console** tab to access the logs).      
Do the *Firing Magnet* messages have the DLPath at the end, like mine do?
![image](https://user-images.githubusercontent.com/6933240/35546387-e4d43f94-05d8-11e8-9187-b60afa420333.png)

**Comment by garfield69** [comment] 2018-01-30 03:24
Also, try changing the qBt download settings to this:
![image](https://user-images.githubusercontent.com/6933240/35546645-fe90f3fe-05d9-11e8-9c79-ac0ba6810fee.png)

**Comment by spmilden** [comment] 2018-01-30 03:39
The Firing Magnet msg has null at the end which is different than yours. I just changed the settings in qbt, quit and restarted and the dl path is still the default. 
![developer log](https://user-images.githubusercontent.com/35412880/35547104-2edff8c4-0545-11e8-966d-e3a1f215dbd4.jpg)

**Comment by garfield69** [comment] 2018-01-30 04:01
but you have already downloaded HtGAwM s04e01 before, so unless you deleted the torrent and files, qBt could cheat and claim the download was done already.... have you tried it with a never downloaded before torrent?

**Comment by spmilden** [comment] 2018-01-30 18:03
Thanks again for your continued help with this. FYI I had deleted the torrent and the files but just to make sure I just tried downloading a show from back in September that qbt has never downloaded. It's still going to the default dl path.
![dtv dl settings](https://user-images.githubusercontent.com/35412880/35582479-f539d5c2-05bc-11e8-9c05-b2cec582601c.jpg)
![qbt save path](https://user-images.githubusercontent.com/35412880/35582653-628ed456-05bd-11e8-8e49-085193ad2eaf.jpg)

**Comment by garfield69** [comment] 2018-01-30 18:22
well that is frustrating.  We know that DTV is sending the path to qBt (your DTV log confirms it), so the problem has got to be in one of the qBt settings someplace.     
Comparing your qBt download settings with mine, I see that there a three other settings that are different. So perhaps try those?
![image](https://user-images.githubusercontent.com/6933240/35583618-6a80bde2-0657-11e8-844a-1b74d48a1272.png)

**Comment by garfield69** [comment] 2018-01-30 19:13
Thinking about this some more, I'm beginning to wonder if qBt hasn't glitched it's config somehow, either when you backtracked down from 4.0.3 to 4.0.2, or because of a bug that treats some of the settings you previously made unchangeable or some such weirdness.
So as a last resort, you could try to uninstall qBt completly, then also scour manually for qBt folders, such as `C:\Users\<username>\AppData\Local\qBittorrent` and `C:\Users\<username>\AppData\Roaming\qBittorrent` and delete those folders.
Then from a fresh install, set the settings and see if that helps.

**Comment by spmilden** [comment] 2018-01-30 23:01
Thanks -unfortunately no change. BTW I'm not committed to qbt if you have better luck with a different client.

**Comment by garfield69** [comment] 2018-01-31 18:55
Oh well, seeing as you cannot get qBt to work for you (works for me so I don't know what is going on), then you might as well try out one of the other clients that support dl-paths.
Currently one of  BiglyBT, Deluge, rTorrent, Transmission, Vuze.

**Comment by spmilden** [comment] 2018-02-01 16:12
I just tried BiglyBT, Transmission, Vuze and Deluge with the same result, i.e., went to the default dl folder. I exited each client and dtv then restarted. Puzzling... So none of the clients will accept changing the dl folder from dtv. My assumption is that that problem exists with dtv since it's the common thing. What about doing a clean install of dtv? If so is there a way to save the list of shows so I don't have to reselect each of them without potentially contaminating the install?

**Comment by garfield69** [comment] 2018-02-01 19:33
So for some reason the torrent clients are rejecting your choice of drive... and you say there is nothing in the logs of any of the torrent clients that gives an explanation?
Is there anything peculiar about the **G** drive that you are using as a destination? 
Is it a NTFS local drive, or a mapped NTFS lan drive?
Is the **I** drive the same type and location as the **G** drive?
I've tested all the clients that can set dl path with both local and lan mapped NTFS drives and I can get my DTV to download to them all.
So it has to be something peculiar with your set up *some place* !!
What about as a one time TEST, setting the dl path to your local **C** drive?

**Comment by spmilden** [comment] 2018-02-02 00:21
I have a media server with five 2 tb drives - all are internal NTFS so there is no difference between the G and I drives. I'll try setting the dl path to C and see what happens. Any thoughts as to what I might check re my system set up? There's nothing I did when installing Windows 7 other than standard set up.

**Comment by garfield69** [comment] 2018-02-02 01:23
So DTV and the torrent clients are running on this windows media server and therefore the G drive is a locally accessed drive?
or is the windows system that runs DTV and the torrent clients on one machine, and the media server G drive is a mapped network drive?
If you access the torrent client WEBUI directly (from the chrome browser, without going through DTV), and create a torrent by pasting the magnet to the *add-a-torrent* panel, and specify a download path override to G (assuming that the default is still to drive I), does that work?

**Comment by spmilden** [comment] 2018-02-02 02:30
Using the C drive as the default dl made no difference. All of the drives are locally accessed. Sorry but I don't know how to access the WEBUI via Chrome.

**Comment by garfield69** [comment] 2018-02-02 02:35
ok. which torrent client are you using now? what is the port number in the torrent client webui setup panel?       
[edit] I'll then knock up some instructions for you to create the test I'd like you to try next.

**Comment by spmilden** [comment] 2018-02-02 17:11
Vuze and the port is 9091

**Comment by garfield69** [comment] 2018-02-02 20:56
Ah well that is a shame. Vuze's remote webui browser panel does not support submitting magnets with a custom path, it uses the default path only. (Tested on Chrome browser, Firefox and IE). I can get my DTV to submit the custom dl path to vuze, so it must just be that plugin (Vuze Web Remote 0.6.5) that does not support changing paths.      
Not useful for the test I was planning for you to try out.

How about Transmission:
1. at the chrome browser address box paste `http://127.0.0.1:9091`
2. and at the challenge login with your transmission webui username and password
#### pic of login panel
![image](https://user-images.githubusercontent.com/6933240/35753996-b1de5570-08c6-11e8-9fbf-fc76b995e431.png)
3. click on the *open-torrent* icon, paste the following magnet in the URL box and paste the following path to replace the default download path 
#### magnet
```
magnet:?xt=urn:btih:931E0A390EB76C67CEF07A598AF7B03F820D5B23&dn=How.to.Get.Away.with.Murder.S04E01.HDTV.x264-KILLERS&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
```
#### path
`G:\TV Shows\How To Get Away With Murder`
#### pic of open-torrent panel
![image](https://user-images.githubusercontent.com/6933240/35754201-75c58972-08c7-11e8-91c1-f748a5f87a72.png)
3. when the upload is successful, click on the *Info* icon then select the active torrent to view the details
#### pic of active transmission with custom path
![image](https://user-images.githubusercontent.com/6933240/35754281-cb12c94e-08c7-11e8-866a-df502c554cee.png)
**Note** in my pic I'm using a different dlpath because I don't have a *G* drive ;-)
Your dl path should not be the default, which for transmission is usually `C:\Users\<username>\Downloads`

Did it work for you?

**Comment by spmilden** [comment] 2018-02-03 00:27
I'll give it a try and let you know.

**Comment by spmilden** [comment] 2018-02-06 00:13
I can't get Transmission to completely load. I've uninstalled and reinstalled it twice with the same result. Can I perform the test with qbt or another client?

**Comment by garfield69** [comment] 2018-02-06 05:04
Sure. So for qBt:
1. at the chrome browser address box paste `http://127.0.0.1:8090` or `http://localhost:8090`
2. and at the challenge popup, login with your qBt webui username and password
#### pic of login panel
![image](https://user-images.githubusercontent.com/6933240/35842384-98b9125e-0b66-11e8-9bb3-a674708db803.png)
3. click on the *add-torrent-link* icon, paste the following magnet in the URL box and paste the following path to replace the default download path 
#### magnet
```
magnet:?xt=urn:btih:931E0A390EB76C67CEF07A598AF7B03F820D5B23&dn=How.to.Get.Away.with.Murder.S04E01.HDTV.x264-KILLERS&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce
```
#### path
`G:\TV Shows\How To Get Away With Murder`
#### pic of add-torrent-link panel
![image](https://user-images.githubusercontent.com/6933240/35842467-233e642e-0b67-11e8-8ba5-8d7eb17c0881.png)
4. scroll down the popup and click on the download button
#### pic of the download button
![image](https://user-images.githubusercontent.com/6933240/35842508-6759fe70-0b67-11e8-868d-d9d31e00f614.png)
5. when the torrent has loaded successfully, select the active torrent to view the details
#### pic of active qBt with custom path
![image](https://user-images.githubusercontent.com/6933240/35842569-c9fa00d4-0b67-11e8-9422-420207b7a337.png)


Did it work for you?

**Comment by spmilden** [comment] 2018-02-07 01:26
It worked just fine! What now?

**Comment by garfield69** [comment] 2018-02-07 01:47
now we are going to see if using a duckietv chrome browser extension works, so we can check if the problem is isolated to your standalone or not.       
so for this test, i'd like you to:
1. startup your standalone DuckieTV and make a backup using the *Settings > backup > Create a Backup* side panel.
2. shutdown the standalone DuckieTV.
3. install this nightly chrome extension https://chrome.google.com/webstore/detail/duckietv-browser-action-m/ikhklcamhmfmjbhckdjoabiepglbhaid
4. wait for DTV to complete its first time initialisations (should take a couple minutes or so) and import your backup.
5. start your qBt and connect your DTV extension to it.
6. test downloading a torrent for a series with the DLpath set.
7. report back :-)

**Comment by spmilden** [comment] 2018-02-07 02:13
Not sure about how to "connect your DTV extension to it"? Do you mean set qbt as the torrent client?

**Comment by garfield69** [comment] 2018-02-07 02:24
DTV is my shorthand for DuckieTV. Assuming that you last use of the standalone was set to trying to use transmission, the backup you imported to your chrome extension DTV will now also be set to use that client connection. So all I meant was set up DTV to use the qBt 3.2+ client integration so you can connect with your qBt client.

**Comment by spmilden** [comment] 2018-02-07 02:41
I understood DTV. I just wasn't clear about connecting the DTV extension to it. I did so and it goes to the default folder rather than the specified dl path. BTW I unchecked the setting in qbt under the Downloads section "Display torrent content and some options" as it requires user input before it will start the download.  If I check it I have the option of setting the dl path each time which defeats the intention of automating the process. Other than that my settings in qbt are exactly the same as yours.

**Comment by garfield69** [comment] 2018-02-07 02:50
>BTW I unchecked the setting in qbt under the Downloads section "Display torrent content and some options" as it requires user input before it will start the download. If I check it I have the option of setting the dl path each time which defeats the intention of automating the process. 


WAIT. That does not sound right. That option only comes into effect if you submit a torrent via the qBt GUI. 
When you tried the Chrome Browser WEBUI directly, you did not get that user input panel when you used the add-a-torrent, did you?
Are you saying that up to now, every time you has DTV submit a torrent you have been getting that pop up?

**Comment by garfield69** [comment] 2018-02-07 02:55
Please check your DTV settings, is the *Torrent Parameters* disabled?
![image](https://user-images.githubusercontent.com/6933240/35896060-3cf192fc-0c1f-11e8-97bf-4ead53f990f6.png)

**Comment by spmilden** [comment] 2018-02-07 03:01
It is enabled - should it be disabled?

**Comment by garfield69** [comment] 2018-02-07 03:01
Aha!!!! turn it off and try your test again.

**Comment by spmilden** [comment] 2018-02-07 03:44
That did it! Thank you - thank you!!!

Now I assume I can go back to the standalone, uncheck the same setting and not need to use Chrome. Yes/no?

BTW I get an I/O error from qbt. This is from the log file: "(N) 2018-02-06T22:14:47 - An I/O error occurred, 'NCIS.S15E14.HDTV.x264-LOL[eztv].mkv' paused. NCIS.S15E14.HDTV.x264-LOL[eztv].mkv open (G:\TV Shows\NCIS\NCIS.S15E14.HDTV.x264-LOL[eztv].mkv) error: The process cannot access the file because it is being used by another process"  When the error shows the torrent Status shows Stalled.  
This happens for all active torrents. 

I never had this happen with utorrent and the only change to my system is Chrome and qbt. Any ideas on how to find out what the offending process is?

**Comment by garfield69** [comment] 2018-02-07 04:01
>That did it! Thank you - thank you!!!

\o/

>Now I assume I can go back to the standalone, uncheck the same setting and not need to use Chrome. Yes/no?

Yes. use the Trash bin on the Chrome Extensions manager to remove the now redundant testing DTV extension.

>Any ideas on how to find out what the offending process is?

Geesh :-b If it's not one thing its another ;-)
Do you think your Plex is getting in the way? is it a Service that is always running, or a program you can stop/start until the download is completed?

**Comment by garfield69** [comment] 2018-02-07 04:05
Pehaps using the qBt option to make incomplete files suffixed with !qB  may stop Plex assuming the file is ready for meta processing.

![image](https://user-images.githubusercontent.com/6933240/35898035-0289de4e-0c29-11e8-9812-2fbdbc7a7253.png)

**Comment by spmilden** [comment] 2018-02-07 18:26
I had the same thought about Plex so stopped the server but it didn't make any difference. I then suspected antivirus but stopping that made no difference either. I just changed the setting in qbt you suggested but it didn't make any difference. 

I searched online for the error and it seems to be a common problem with qbt going back to 2013 with no solutions that I've found so far. Any recommendation for another bt client other than Transmission which I can't get to load properly that will allow dtv to set the dl path?

**Comment by garfield69** [comment] 2018-02-07 18:30
Try BiglyBT.

**Comment by spmilden** [comment] 2018-02-08 01:17
I think I figured out what was causing the I/O error. I stopped all of Cyberlink Power DVD's processes and the I/O error hasn't reappeared. Now that qbt seems to be working properly I'll hold off making any other changes.  Thanks again for your help and patience.
