### ISSUE TITLE
Error Message When Running Standlone 1.1.4

### ISSUE THREAD

**Issue by GumboMKX** [SchizoDuckie/DuckieTV#881] opened 2017-03-25 03:29 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standlone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows XP - 32 Bit

**Describe the problem you are having and steps to reproduce if available**
I have no problem running Standlone 1.1.3 but if I install and run Standlone 1.1.4.  I get the following error message and the software doesn't run.

**DuckieTV.exe - Entry Point Not Found
The procedure entry point ReleaseSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll**

I can also provide a screenshot of this error message if it would help.  Was 1.1.4 changed so it doesn't work with Windows XP anymore?

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2017-03-25 06:25
As you may know, DuckieTV is written with *AngularJS*, a JavaScript framework, originally as a Chrome Browser extension.    
Later we found a 3rd party run time environment called NW.js which allows us to package our DuckieTV scripts to run without the Chrome Browser, thus the Standalone releases were born.      
DuckieTV 1.1.3 used NW.js 0.12.3, which at that time supported windows XP.     
But with DuckieTV 1.1.4 we upgraded to using NW.js 0.21.1, to take advantage of the new features and services that became available since Chromium 54.      

However NW.js only supports windows XP with their Long Term Support (LTS) version 0.14.x which remains fixed on Chromium 50.     

So it should be possible for you to continue to run the latest version of DuckieTV, but not in the pre-packaged Standalone releases that we currently build. To make it work you are going to have to put together yourself.     

If you are keen to give it a go, then start by reading the following wiki https://github.com/SchizoDuckie/DuckieTV/wiki/How-to-Install-a-Development-version-of-the-Windows-DuckieTV-Standalone-SOURCE     
But instead of downloading the *Latest NWJS Stable SDK*, grab the latest LTS as explained in hte pre-requisites section.     

I no longer have a Windows XP sandbox, so I cannot provide any support or even guarantee that it will all work as intended, you will be testing on your own with this one.     
If you decide to go ahead, then good luck and best wishes. :-)

**Closed as completed** 2017-03-25 06:25 UTC
Labels: question

**Comment by GumboMKX** [comment] 2017-03-25 09:27
I was able to follow the instructions and I have been able to get the DEV running and it's listed as 1.1.5 but I noticed a few problems.

1.  When I click on "Add a show" and start typing the name of a show, it gives me the message that there was an error connecting to TrakT.TV and it might be down.  I checked the TrakT.TV site and it's up and running.
2. Under Settings, Backup, I'll click "Refresh All Series" and nothing happens.  Connected to TrakT.TV?
3. There is no images/artwork in the background of the calendar pages.

I know the images/artwork got changed.  Do I need to change a link for the images/artwork and updates?

**Comment by garfield69** [comment] 2017-03-25 17:43
>I was able to follow the instructions and I have been able to get the DEV running and it's listed as 1.1.5      

Terrific, well done.      

>I click on "Add a show" and start typing the name of a show, it gives me the message that there was an error connecting to TrakT.TV and it might be down. I checked the TrakT.TV site and it's up and running.     

The Trakt.tv servers that handle the WEB site pages are not the same ones that Trakt.TV uses for the API requests that DuckieTV makes.     
I was able to get DuckieTV Trakt.tv updates this morning, so I suggest you try again.     
If you are still getting error connection issues, then you can take a look at the log to get a more complete error message that may explain/help with what is going on.      
To open the log, first press **F12** to open the *Development Tools* page, then click on the **console** tab to view the log.     

>Under Settings, Backup, I'll click "Refresh All Series" and nothing happens. Connected to TrakT.TV?     

Yes, all Series, season and episode data is fetched from Trakt.Tv via their API servers.     

>There is no images/artwork in the background of the calendar pages.     
>I know the images/artwork got changed. Do I need to change a link for the images/artwork and updates?      

No, you should not need to touch the FanArt.tv address. But if none of the images are being fetched, then this may be a symptom of a larger problem: maybe ALL your DuckieTV tcp/ip traffic is failing. This might explain the Trakt.tv connections errors, as well as FanArt.tv.      
I would suggest shutting down and restarting DuckieTV, then viewing the log looking for the first signs of errors. Something does not appear to be working as it should.

**Comment by GumboMKX** [comment] 2017-03-26 01:12
> If you are still getting error connection issues, then you can take a look at the log to get a more complete error message that may explain/help with what is going on.
To open the log, first press F12 to open the Development Tools page, then click on the console tab to view the log.

I opened the program and did what you said and I was able to get the log file and I can see where the program is having a lot of trouble connecting to a localhosts and to the fanart site.  I've attached the log file, hoping you can look at it and make heads or tails of what I can do next?  I appreciate all the help!

[bagblfnohpiddokbpaacecffdboomafe-1490490587445.pdf](https://github.com/SchizoDuckie/DuckieTV/files/870492/bagblfnohpiddokbpaacecffdboomafe-1490490587445.pdf)

**Comment by garfield69** [comment] 2017-03-26 02:52
Ah. Your log is full of ERR_INSECURE_RESPONSE for all the Trakt.tv and FanArt.tv requests.    

So what I think is going on here, is that the chromium 50 browser that is built into the nw.js 0.14.7 that you are using, does not have any of the current security certificates that nearly all web site are using for https encryption these days.    

A solution is to switch to http instead, but the caveat is that obviously this leaves you exposed, as all your traffic will be coming and  going  as unsecured, plain non-encrypted text.    
It also means any site that requires a login will probably fail, since they will insist you use https, which you cannot support on window xp through nw.js and chromium.    

With this in mind, should you want to continue, then edit with a plain text editor the following files: js/services/TraktTVv2.js line 15    
and js/services/FanartService.js line 6     
replacing https with http    
and see if that works.

**Comment by GumboMKX** [comment] 2017-03-26 11:11
I changed the two lines and loaded up the program.

The calendar is not showing a background image for the whole month.  Not sure if this feature was removed or not?
I clicked on "View Your Favorites" and all my shows are showing up but without images.
I clicked on "Add a show" and the shows listed show images.
The search box does do a search from TrakT.TV
Settings/Backup - "Refresh All Series"  This is still not refreshing.

I checked the logs and it does show that it couldn't load up fanart and when trying to do the refresh, it was coming up as 404, not found.

[bagblfnohpiddokbpaacecffdboomafe-1490525567805.pdf](https://github.com/SchizoDuckie/DuckieTV/files/870696/bagblfnohpiddokbpaacecffdboomafe-1490525567805.pdf)

**Comment by SchizoDuckie** [comment] 2017-03-26 11:25
Imo this will lead into multiple unpredictable results requiring much more
support that we just cannot give. XP is a deprecated platform after all
these years, it's time to either convert your old pc to Ubuntu or learn to
live with broken software.

Imo we should stop trying to support XP users. As it's becoming too much of
a burden on us.

HTTPS support is broken, which breaks the web. 
Upgrade your pc instead of transferring the burden of support onto an open source project.

**Comment by Js41637** [comment] 2017-03-26 11:38
XP is the new IE8, it should be forgotten.

**Comment by GumboMKX** [comment] 2017-03-27 04:14
> Imo we should stop trying to support XP users. As it's becoming too much of a burden on us. HTTPS support is broken, which breaks the web.

> Upgrade your pc instead of transferring the burden of support onto an open source project.

First, let me thank Garfield69 for taking the extra time and attention to answer my questions and look into the issues I am having with the software.  I appreciate Garfield69 for the suggestions on how to possibly fix the software.

Second, I'm sorry if asking why software isn't working is a burden and I never asked to be a special case just because I ran the software on Windows XP.  I only asked because when I originally installed the software, it was version 1.1.3 Standalone and it installed to Windows XP but then 1.1.4 Standalone has issues and bugs.  In my original post, I even asked if the software was changed if it doesn't work on Windows XP because I couldn't find anywhere stating that it no longer did.

**Comment by garfield69** [comment] 2017-03-27 04:25
Ah well, it was a good try, but it looks like fanart.tv is refusing to supply series image links on http.     
Still, you got trakt.tv data, so we got a lot further that I ever thought we would.     
But now I know for certain we cannot support XP, so I will now update our wiki to indicate this.     
Thanks for giving it a go.

**Comment by SchizoDuckie** [comment] 2017-03-27 12:09
Sorry, I meant no offense and hijacked your issue thread to make this
comment in a more general direction.

It has nothing to do with you or the reason you're still running XP!

I still hope you can see my point of view though

Op 27 mrt. 2017 2:05 p.m. schreef "GumboMKX" <notifications@github.com>:

Imo we should stop trying to support XP users. As it's becoming too much of
a burden on us. HTTPS support is broken, which breaks the web.

Upgrade your pc instead of transferring the burden of support onto an open
source project.

First, let me thank Garfield69 for taking the extra time and attention to
answer my questions and look into the issues I am having with the software.
I appreciate Garfield69 for the suggestions on how to possibly fix the
software.

Second, I'm sorry if asking why software isn't working is a burden and I
never asked to be a special case just because I ran the software on Windows
XP. I only asked because when I originally installed the software, it was
version 1.1.3 Standalone and it installed to Windows XP but then 1.1.4
Standalone has issues and bugs. In my original post, I even asked if the
software was changed if it doesn't work on Windows XP because I couldn't
find anywhere stating that it no longer did.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/SchizoDuckie/DuckieTV/issues/881#issuecomment-289350123>,
or mute the thread
