### ISSUE TITLE
ruTorrent support

### ISSUE THREAD

**Issue by KsaRedFx** [SchizoDuckie/DuckieTV#631] opened 2016-01-27 23:30 UTC
Add remote ruTorrent Support <3

**Comment by garfield69** [comment] 2016-03-07 05:08
preliminary research:
ruTorrent is a front-end for rtorrent (a console based BitTorrent client). It runs under a web-server on linux systems, and uses rTorrent's built-in XML-RPC server to communicate with it.

So from what I have found so far, ruTorrent is not a candidate for the existing DuckieTV WEBUI Client  model, as it is itself a WEBUI client, not a torrent Host.

ticket #452 requests looking into creating a WEBUI client for rTorrent. We may be able to shortcut development by seeing how ruTorrent interfaces with rTorrent (it uses xmlrpc).

ruTorrent official site: [https://github.com/Novik/ruTorrent](https://github.com/Novik/ruTorrent)
ruTorrent wiki [https://github.com/Novik/ruTorrent/wiki](https://github.com/Novik/ruTorrent/wiki)
rTorrent official site:[https://rakshasa.github.io/rtorrent](https://rakshasa.github.io/rtorrent)

**Comment by KsaRedFx** [comment] 2016-03-07 05:10
That was kinda the idea. Since it already uses the xmlrpc communication with rtorrent, and people who are running ruTorrent are more likely to use rtorrent it with DuckieTV than anyone else.

**Comment by garfield69** [comment] 2016-03-07 05:34
closing as a duplicate of #452

**Closed by garfield69** 2016-03-07 05:34 UTC
Labels: 0 - Backlog, enhancement request
