### ISSUE TITLE
angular-translate-once

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#454] opened 2015-06-02 18:49 UTC
http://atticuswhite.com/blog/angularjs-translate-once-angular-translate-one-time-binding/

Just came across this.

**Comment by garfield69** [comment] 2015-06-03 02:32
I'll implement this, but it is going to take a back-seat while the Roland Garros French Grand Slam Tennis is on, as well as the Formula One in Canada this weekend.
So if anyone wants to implement this sooner, feel free to do so, and indicate possession of the ticket by self assigning it :-)

**Comment by Js41637** [comment] 2015-06-03 07:46
#357

**Comment by SchizoDuckie** [comment] 2015-06-03 16:37
@garfield69  enjoy!

**Comment by garfield69** [comment] 2015-06-04 07:36
notes: 
seeing as we seem to be looking for performance lately, it is well overdue that we examine how we are using $translate.
For starters, we should ditch using interpolated filtered translations of just plain text. 
This has multiple benefits:
1. a huge reduction in watched expressions, as multiple filters = multiple watchers, 
2. doing without interpolation gives a performance benefit as there is one less pass to do before view,
3. and translate-once only supports directives, so ditching the filter is a pre-requisite.

so I will need to replace
```javascript
                <i class="glyphicon glyphicon-info-sign"></i><strong>{{'SIDEPANEL/EPISODE-DETAILS/series-details/btn'|translate}}</strong>
```
with
```javascript
                <i class="glyphicon glyphicon-info-sign"></i><strong translate>SIDEPANEL/EPISODE-DETAILS/series-details/btn</strong>
```

**Comment by garfield69** [comment] 2015-06-05 05:04
template conversion list
- [ ] about.html
- [ ] chrome-top-sites.html
- [ ] datepicker.html
- [ ] episodeDownloaded.html
- [ ] episodeWatched.html
- [ ] event.html
- [ ] querymonitor.html
- [ ] serieHeader.html
- [ ] serieslist
- [ ] seriesList.html
- [ ] settings
- [ ] sidepanel
- [ ] subtitleDialog.html
- [ ] torrentClient.html
- [ ] torrentDialog.html
- [ ] torrentFreakTop10.html
- [ ] torrentMiniRemoteControl.html
- [ ] torrentMiniRemoteProgress.html
- [ ] torrentRemoteControl.html
- [ ] typeAheadIMDB.html
- [ ] typeAheadSeries.html
- [ ] upgrade.html
- [ ] watchlist.html
- [ ] serieslist\favorites.html
- [ ] serieslist\searchresults.html
- [ ] serieslist\tools
- [ ] serieslist\trakt-searching.html
- [ ] serieslist\trakt-trending.html
- [ ] serieslist\tools\adding.html
- [ ] serieslist\tools\favorites.html
- [ ] serieslist\tools\localfilter.html
- [ ] settings\backup-import.html
- [ ] settings\backup.html
- [ ] settings\calendar.html
- [ ] settings\custom-search.html
- [ ] settings\deluge.html
- [ ] settings\display.html
- [ ] settings\language.html
- [ ] settings\qbittorrent.html
- [ ] settings\qbittorrent32plus.html
- [ ] settings\sync.html
- [ ] settings\tixati.html
- [ ] settings\torrent-search.html
- [ ] settings\torrent.html
- [ ] settings\trakt-import.html
- [ ] settings\trakttv.html
- [ ] settings\transmission.html
- [ ] settings\utorrent.html
- [ ] settings\utorrentwebui.html
- [ ] settings\vuze.html
- [ ] sidepanel\episode-details.html
- [ ] sidepanel\episodes.html
- [ ] sidepanel\mark-downloaded.html
- [ ] sidepanel\mark-watched.html
- [ ] sidepanel\seasons.html
- [ ] sidepanel\serie-details.html
- [ ] sidepanel\serie-overview.html
- [ ] sidepanel\settings.html
- [ ] sidepanel\sidepanel.html
- [ ] sidepanel\torrent-details.html
- [ ] sidepanel\torrentRemoteControl.html
- [ ] sidepanel\trakt-serie-details.html

**Comment by garfield69** [comment] 2015-06-05 19:00
I thought I was being clever by getting translate-once to handle tooltip translations, but ui-bootstrap is too clever for me. [check this out:](https://github.com/ajwhite/angular-translate-once/issues/1)
:blush:

**Comment by SchizoDuckie** [comment] 2015-06-05 19:05
:+1: awesome work! interesting race condition you have there... could solved with ab directive priority
 maybe?

**Comment by ajwhite** [comment] 2015-06-05 19:07
The problem is that the one-time translation is asynchronously resolved, rather than synchronously. So it doesn't finish at the time of linking, it's instantiated at the time of linking. `ui-bootstrap` builds the tooltip synchronously during linking, and does not observe any changes. Further discussion over in https://github.com/ajwhite/angular-translate-once/issues/1

**Comment by garfield69** [comment] 2015-06-05 21:36
@SchizoDuckie.
So in the end, I got the translate-once to operate on a tooltip.
However, to do so I have had to create a dedicated template.
example below:
```javascript
<h2>{{date|date:"MMMM yyyy"}} <i tooltip-template="'calendarMonthView.html'" class="glyphicon glyphicon-chevron-down" ng-click="setView('date')"></i>
</h2>
[...]
<script type="text/ng-template" id="calendarMonthView.html">
  <span translate-once="DATEPICKER/calendar-monthview/glyph/tooltip"></span>
</script>
```
But I would have to create a template for each and every tooltip I want translated once. 
seems to be that this in no more efficient that just leaving the original tooltip with the translation filter in place,
what do you think?

**Comment by SchizoDuckie** [comment] 2015-06-05 22:09
Hmm I would say that's way too much overhead. Then let's just benefit from
translate-once where we can and use it pragmatically. It's supposed to
help, not be a PITA :)

**Comment by garfield69** [comment] 2015-06-06 06:40
I think I'm done. Please report any omissions, errors, or suggestions for improvements. Thanks.

**Closed** 2015-06-10 06:10 UTC
Labels: 3 - Done, enhancement
