### ISSUE TITLE
Can't connect qbittorrent v4.0.3

### ISSUE THREAD

**Issue by spmilden** [SchizoDuckie/DuckieTV#1025] opened 2018-01-20 18:00 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...Nightly V201801140130

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows

**Describe the problem you are having and steps to reproduce if available**
...Trying to connect qbittorrent v4.0.3 and am getting an error which can be seen in the attached screenshot. I've double checked the username and password in both apps and followed the instructions to the letter from "Setting up qBitTorrent 3.2 with DuckieTV"
![duckietv error](https://user-images.githubusercontent.com/35412880/35186402-96d94d56-fde1-11e7-8a60-b4c867d0bf1b.jpg)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2018-01-20 18:03
Duplicate of #1009
Yes, qBt made a change in 4.0.3 that broke the DuckieTV qBt client interface. qbittorrent/qBittorrent@b827761 fixes this problem, which will be included in the next qBt release, whenever that gets published.
The problem cannot be fixed by DuckieTV, so 4.0.2 is the current compatible client.

**Closed as completed by garfield69** 2018-01-20 18:03 UTC
Labels: duplicate

**Comment by spmilden** [comment] 2018-01-20 18:33
Thanks for the speedy reply. I'm changing from utorrent because I want to set specific download folders for each TV show. Do you recommend another client or just install 4.0.2 until the next release?
[Update]
I just installed v4.0.2 and am having the same problem. Below is an extract from the Console. BTW I substituted * for the password.

Failed to load resource: the server responded with a status of 400 (ERROR)
app.js:3724 qBittorrent 3.2+ connect error! Object
(anonymous) @ app.js:3724
spmilden:*******@localhost:8080/version/api Failed to load resource: net::ERR_CONNECTION_REFUSED
deps.js:2354 qBittorrent 3.2+ Connect call failed.
(anonymous) @ deps.js:2354
app.js:3724 qBittorrent 3.2+ connect error! qBittorrent 3.2+ Connect call failed.
(anonymous) @ app.js:3724

**Comment by garfield69** [comment] 2018-01-20 18:39
>Do you recommend another client or just install 4.0.2 until the next release?

 install 4.0.2 until the next release

**Comment by 2635599** [comment] 2018-01-20 18:46
spmilden you might want to look at the date i opened this. i haven't responded back here cause i got this answered in the duckietv reddit forum. this can actually be closed.

**Comment by garfield69** [comment] 2018-01-20 18:57
@spmilden  4.0.3 returns 401.
On 4.0.2 you are seeing 400, a different error.
I suggest you shutdown both qBt and DuckieTV, start qBt and then start DuckieTV
Then check carefully that you have used the correct port, address, username and password.
If you need to confirm you have the right details, use your Chrome Browser to logon directly to the qBt webpage.
Remember that DuckieTV only saves the logon details when it has succeeded connecting, so you may need to re-enter logon details between attempts.

**Comment by spmilden** [comment] 2018-01-20 19:59
I did as you suggested and still get the 400 error. Everything is correct as far as port, address, username and password.

**Comment by garfield69** [comment] 2018-01-20 20:04
you've opened 1026 so lets use that now.
