### ISSUE TITLE
Uncaught (in promise) ERROR!ReferenceError: openDatabase is not defined

### ISSUE THREAD

**Issue by RayMN** [SchizoDuckie/DuckieTV#1403] opened 2023-11-25 00:54 UTC
**What build of DuckieTV are you using (Chrome Extension (New Tab / Browser Action))**
```
Tried both ... same errors
DuckieTV - 'Browser Action' mode - Nightly 3023.11.1.1075
```

**What is your Operating System (Windows, MacOSx, Linux)**
`Ubuntu 22.04.3 LTS`

**Describe the problem you are having and steps to reproduce if available**
```
I can't get either DuckieTv Chrome Extension to run on Ubuntu 22.04.3 LTS
Using Chrome: Version 119.0.6045.105 (Official Build) (64-bit)
My extension manager says I'm in Developer mode.
I get these error for both newtab and browseraction:
1) Warning: Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
2) Warning: Optional permission 'http://*/*' is redundant with the required permissions;this permission will be omitted.
3) Warning: Optional permission 'https://*/*' is redundant with the required permissions;this permission will be omitted.
4) Uncaught (in promise) ERROR!ReferenceError: openDatabase is not defined
    Context
        _generated_background_page.html
    Stack Trace
        _generated_background_page.html:0 (anonymous function)

I can see the extension in the manager with these errors but the extension is not available in the toolbar.

Since you are still doing updates to it I don't think it's dead.
My other extensions are:
AdBlock 5.14.0
ExpressVPN 5.2.6.5291
uBlock Origin 1.53.0
```

**Attach any DuckieTV statistics or Developer Console logs if available**
`If you tell me where they are I will provide them, I looked and can't seem to find them.`

![browseraction_2023-11-01_1754](https://github.com/SchizoDuckie/DuckieTV/assets/10171295/47702030-393c-43f4-8e10-1e7ed2ed5119)

**Comment by garfield69** [comment] 2023-11-25 00:57
read https://github.com/SchizoDuckie/DuckieTV/issues/1399#issuecomment-1789353212
closing as duplicate of #1399
And of course, if this does not solve the problem please report back and we can re-open the ticket and do more diag.
[edit: fixed cut/paste typo]

**Closed as completed by garfield69** 2023-11-25 00:57 UTC
Labels: duplicate

**Comment by garfield69** [comment] 2023-11-25 01:00
BTW warnings 1,2 and 3 can be ignored for now.

**Comment by RayMN** [comment] 2023-11-25 01:04
> BTW warnings 1,2 and 3 can be ignored for now.
Figured, just included them for context if needed.

> read [#1399 (comment)](https://github.com/SchizoDuckie/DuckieTV/issues/1399#issuecomment-1789353212) closing as duplicate of #1399 And of course, if this does not solve the problem please report back and we can re-open the ticket and do more diag. [edit: fixed cut/paste typo]

This worked and I'm back in business!!
THANKS! :)
