### ISSUE TITLE
Can't Integrate with QBittorrent

### ISSUE THREAD

**Issue by teknikel** [SchizoDuckie/DuckieTV#1039] opened 2018-02-27 00:32 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...1.1.4

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 10

**Describe the problem you are having and steps to reproduce if available**
... Haven't been able to integrate DuckieTV and Qbittorrent. I have done  everything in the help link.

**Attach any DuckieTV statistics or Developer Console logs if available**
... 

User Preferences on Local Storage | {   "KickAssTorrents.mirror": "https://kat.cr",   "ThePirateBay.mirror": "https://accesspiratebay.com/",   "application.language": "en_us",   "application.locale": "en_us",   "autodownload.minSeeders": 100,   "autodownload.period": 1,   "background-rotator.opacity": "0.45",   "main.viewmode": "calendar",   "calendar.mode": "date",   "calendar.show-specials": false,   "calendar.show-downloaded": true,   "calendar.show-episode-numbers": true,   "calendar.startSunday": true,   "client.determinedlocale": "en_us",   "download.ratings": true,   "lastSync": -1,   "library.smallposters": false,   "library.seriesgrid": false,   "kc.always": false,   "qbittorrent.server": "http://localhost",   "qbittorrent.port": 8080,   "qbittorrent.use_auth": true,   "qbittorrent.username": "admin",   "qbittorrent.password": "*****",   "qbittorrent32plus.server": "http://localhost",   "qbittorrent32plus.port": 8080,   "qbittorrent32plus.use_auth": true,   "qbittorrent32plus.username": "doingbiz",   "qbittorrent32plus.password": "*****",   "series.displaymode": "poster",   "storage.sync": false,   "sync.progress": true,   "tixati.server": "http://localhost",   "tixati.use_auth": true,   "tixati.port": 8888,   "tixati.username": "admin",   "tixati.password": "*****",   "topSites.enabled": false,   "topSites.mode": "onhover",   "torrenting.autodownload": true,   "torrenting.autostop": true,   "torrenting.autostop_all": false,   "torrenting.client": "qBittorrent 3.2+",   "torrenting.directory": true,   "torrenting.enabled": true,   "torrenting.progress": true,   "torrenting.searchprovider": "Zooqle",   "torrenting.searchquality": "",   "torrenting.streaming": true,   "vuze.server": "http://localhost",   "vuze.port": 9091,   "vuze.use_auth": true,   "vuze.username": "doingbiz",   "vuze.password": "*****",   "transmission.server": "http://localhost",   "transmission.port": 9091,   "transmission.use_auth": true,   "transmission.username": "admin",   "transmission.password": "*****",   "trakttv.passwordHash": "*****",   "trakttv.sync": true,   "trakttv.username": null,   "utorrentwebui.server": "http://localhost",   "utorrentwebui.port": 8080,   "utorrentwebui.username": "admin",   "utorrentwebui.password": "*****",   "utorrentwebui.use_auth": true,   "deluge.server": "http://localhost",   "deluge.port": 8112,   "deluge.password": "*****",   "deluge.use_auth": true,   "subtitles.languages": [     "eng"   ],   "autodownload.lastrun": 1497781821051,   "proxy.allowUnsafe": false,   "transmission.path": "/transmission/rpc",   "vuze.path": "/transmission/rpc",   "autodownload.multiSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true,     "KickAss": true   },   "torrenting.ignore_keywords": "720p, 1080p, mkv",   "torrenting.global_size_min": 100,   "torrenting.global_size_max": 700,   "torrentDialog.2.enabled": false,   "torrenting.launch_via_chromium": true,   "torrentDialog.2.activeSE": {     "ThePirateBay": true,     "1337x": true,     "IsoHunt": true,     "KATcr": true,     "Nyaa": true,     "RarBG": true,     "ShowRSS": true,     "TorrentDownloads": true,     "TorrentZ2": true,     "Zooqle": true,     "EzTV.ag": true,     "Idope": true,     "LimeTorrents": true,     "SkyTorrents": true,     "KickAss": true   },   "torrenting.ignore_keywords_enabled": true,   "torrentDialog.showAdvanced.enabled": false }
-- | --
Other significant Local Storage keys | {   "1.1.4TorrentHashListCleanup": "Sun Jun 04 2017 23:49:11 GMT-0400 (Eastern Daylight Time)",   "1.1.4cleanupOrphanedEpisodes": "Sun Jun 04 2017 23:49:07 GMT-0400 (Eastern Daylight Time)",   "1.1.4cleanupOrphanedSeasons": "Sun Jun 04 2017 23:49:08 GMT-0400 (Eastern Daylight Time)",   "1.1.4qBittorrentPre32": "Sun Jun 04 2017 23:49:03 GMT-0400 (Eastern Daylight Time)",   "1.1.4refresh": "Sun Jun 04 2017 23:49:13 GMT-0400 (Eastern Daylight Time)",   "1.1.4refreshTrendingCache": "Sun Jun 04 2017 23:49:03 GMT-0400 (Eastern Daylight Time)",   "1.1.4updateDelugeAuth": "Sun Jun 04 2017 23:49:03 GMT-0400 (Eastern Daylight Time)",   "1.1.4updateTransmissionPath": "Sun Jun 04 2017 23:49:03 GMT-0400 (Eastern Daylight Time)",   "1.1migration": "Thu Sep 29 2016 09:59:11 GMT-0400 (Eastern Daylight Time)",   "autobackup.lastrun": "1519690438793",   "database.version.Episodes": "13",   "database.version.Fanart": "1",   "database.version.SearchEngines": "2",   "database.version.Seasons": "6",   "database.version.Series": "15",   "database.version.WatchList": "1",   "database.version.WatchListObject": "1",   "fanart.bootstrapped": "1",   "github.lastupdatecheck": "1475157553770",   "optin_error_reporting": "true",   "optin_error_reporting.start_time": "1519691505203",   "snr.lastFetched": "1519678009612",   "standalone.alwaysShowTray": "Y",   "standalone.closeSystray": "N",   "standalone.minimizeSystray": "Y",   "standalone.position": "{\"width\":1538,\"height\":866,\"x\":0,\"y\":0,\"state\":\"maximized\"}",   "standalone.startupMinimized": "N",   "standalone.trayColor": "-green",   "standalone.zoomlevel": "6",   "torrenting.client": "qBittorrent 3.2+",   "trakttv.lastupdated": "1519678009624",   "trakttv.lastupdated.trending": "1519681342770",   "trakttv.refresh_token": "ba881c3d7298ff17ba1d7f613af92566860741663e7d148e5aba9e433c0795b1",   "uniqueId": "2a6dc97a-0c7c-2e85-3984-6a0b004f051e",   "upgrade.notify": "1.1.4",   "xem.lastFetched": "1519678009605" }

**Comment by garfield69** [comment] 2018-09-17 08:14
urg, just noticed this ticket, Sorry.
Presumably you upgraded to 1.1.5 by now, or even better, one of the later nightly releases with increased qBt compatibility.
did you ever resolve this or have you moved on to something else?
closing, but will reopen in the unlikely event the OP replies that the problem is still outstanding.

**Closed by garfield69** 2018-09-17 08:14 UTC
