### ISSUE TITLE
KDE Neon (and probably other ubuntu derivates) are missing libatomic1 on a fresh install of Duckytv.deb

### ISSUE THREAD

**Issue by TabForce** [SchizoDuckie/DuckieTV#1385] opened 2023-03-18 14:25 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...
Standalone 
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
Different Versions from Jan to March

**What is your Operating System (Windows, Mac, Linux, Android)**
KDE Neon

**Describe the problem you are having and steps to reproduce if available**
DuckieTV won*t start

**Attach any DuckieTV statistics or Developer Console logs if available**
libva error: vaGetDriverNameByIndex()

installing libatomic1 solves the issue

Pleaste make libatomic1 a dependency of DuckieTV when creating a deb

**Comment by garfield69** [comment] 2023-03-18 17:55
similar/duplicate of #1329
https://github.com/SchizoDuckie/DuckieTV/wiki/FAQ#why-does-standalone-dtv-not-work-on-ubuntu21-or-lubuntu21
was added back on Oct 2021.

**Closed as completed by garfield69** 2023-03-18 17:55 UTC
Labels: duplicate
