### ISSUE TITLE
Show does not auto download even though, when 'find torrent' is used there are results

### ISSUE THREAD

**Issue by shadycady** [SchizoDuckie/DuckieTV#588] opened 2015-10-29 09:43 UTC
The Late Show with Stephen Colbert

Show does not auto downloading even though, when 'find torrent' is used there are results which can be selected as magnets and started in uTorrent.  

Other than that I can confirm that the nightly hasn't had any problem and does everything else without my input. Love it.

**Comment by garfield69** [comment] 2015-10-29 16:15
duplicate of #572

**Closed by garfield69** 2015-10-29 16:15 UTC
