### ISSUE TITLE
Connecting DuckieTV and QBittorrent 4.1.5

### ISSUE THREAD

**Issue by geordon49** [SchizoDuckie/DuckieTV#1139] opened 2019-01-07 16:00 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...
V 1.1.5
**What is your Operating System (Windows, Mac, Linux, Android)**
...
Windows 10
**Describe the problem you are having and steps to reproduce if available**
...
DuckieTV thinks I am using QBittorrent 3.2+ and does not pass torrents to QBittorrent 4.1.5
It displays message saying DuckieTV has started download but it is not in QBittorrent 4.1.5
**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2019-01-07 16:13
Duplicate of #1138 
For now dtv can only connect to qBt 4.1.4
Changes in 4.1.5 prevent authorisation.

**Closed as completed by garfield69** 2019-01-07 16:13 UTC
Labels: duplicate
