### ISSUE TITLE
Weird pixelated icon instead of spinning Magnet to indicate a magnet link is downloading

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#825] opened 2017-01-18 15:28 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
latest Dev

**What is your Operating System (Windows, Mac, Linux, Android)**
Mac OS X

**Describe the problem you are having and steps to reproduce if available**
Instead of the spinning magnet I get some pixelated weirdness spinning around, see screenshot attached for below the show Leah Remini: Scientology and the Aftermath

**Attach any DuckieTV statistics or Developer Console logs if available**
n/a

![screen shot 2017-01-18 at 11 27 27 am](https://cloud.githubusercontent.com/assets/13501166/22070065/71ad7702-dd79-11e6-8039-0b50794c4d81.png)
![screen shot 2017-01-18 at 11 27 34 am](https://cloud.githubusercontent.com/assets/13501166/22070066/71b43d94-dd79-11e6-9bb3-0a9bd6ec9210.png)

**Comment by garfield69** [comment] 2017-01-18 19:11
Are you using nwjs 0.19.5 normal (or sdk) or some other version?     
This appears to be a issue with the mac os x flavour of either Chromium or nwjs.     

The glyphicon-magnet rotates cleanly using the latest DuckieTV source code in chrome browser action mode, under Windows 7 x32 Chrome Browser Stable 55.0.2883.87 m, and also using the latest DuckieTV source code in standalone mode with Windows 7 x32 nwjs 0.19.5 SDK (which includes chromium 55.0.2883.87).     
![image](https://cloud.githubusercontent.com/assets/6933240/22078530/29c58282-de1d-11e6-97eb-e5c5a53664a8.png)

We are not doing anything fancy to rotate the magnet, we just use the standard spin class,  `<i class="glyphicon glyphicon-magnet spin" style="float:right" uib-tooltip="Connecting to peers. please wait." tooltip-position="right"></i>`.     
So I think the problem is outside DuckieTV's control. If the problem continues when mac os x nswj upgrade to using chromium 56, we may look at raising a ticket with either the chromium or nwjs team.

**Comment by lonelyfairie** [comment] 2017-01-27 16:49
Hi Garfield, sorry for the late reply. I am using nwjs normal edition 19.5. Anyhow after seeing and documenting the issue I no longer see it, could have been a graphics resource issue with my machine maybe?
It is an old 2013 Macbook Pro so sometimes it gets kinda slow if I am running one too many programs at the same time.

**Comment by garfield69** [comment] 2017-01-27 17:09
A Graphics resource issue sounds plausible.  I will close this ticket.     
On a OS X related matter, if you have the time, and are willing to try out a canary Nightly, @SchizoDuckie  has built an OS X Nightly https://github.com/DuckieTV/Nightlies/releases/download/nightly-01122017/DuckieTV-20170126-OSX-x64.pkg which we would love some independent feedback on how it installs.

**Closed by garfield69** 2017-01-27 17:09 UTC
Labels: bug - edge case, Pending Feedback

**Comment by lonelyfairie** [comment] 2017-02-05 21:52
@garfield69 just installed the nightly version. 
Couple of things I noticed are:

- Even though this version took all the settings and database from my already installed dev version of duckie I found the multiple search engine option disabled, when I re enabled it it did have the same selection of search engines as I had set before. 

- Enabling multiple search engine searchs searchs all of the providers even though I have some deselected on purpose on the settings menu (see screenshots of search and settings)

- I got an error from searching in multiple search engines for Extratorrent:
Error: Malformed UTF-8 data (screenshot attached)

In the screenshot it doesn't find any torrents but when I searched for other series it did return results for other search engines, so the error does not prevent the whole search.

- Estetic errors shown in screenshots, when you position the mouse over the Favorite Shows and Utorrent icon in calendar view.

I am not sure if this was also happening with the dev version or not but I did notice that for shows that have the Ignore Global Quality for this show setting enabled it does set the search quality to All, whereas I remember some time back I reported this was not the case when manually searching for a torrent. 

Personally I would also note that I don't like the scroll bar in the torrent search dialog for reaching the rest of the torrent search engines, I like the other version where it created a second line of text and you can see all search engines at once. But that is just a personal opinion :)

I will test out this version for a couple days at least and if I notice anything else I will report back, if you want me to test anything specific do let me know.

![screen shot 2017-02-05 at 1 17 04 pm](https://cloud.githubusercontent.com/assets/13501166/22630139/ef6b400e-ebd2-11e6-9c8f-5513da60ab5d.png)
![screen shot 2017-02-05 at 1 17 25 pm](https://cloud.githubusercontent.com/assets/13501166/22630140/ef6f7f5c-ebd2-11e6-8623-862f3df525a9.png)
![screen shot 2017-02-05 at 6 28 45 pm](https://cloud.githubusercontent.com/assets/13501166/22630141/ef71ee22-ebd2-11e6-8fa1-b4684b0f2ebe.png)
![screen shot 2017-02-05 at 6 32 40 pm](https://cloud.githubusercontent.com/assets/13501166/22630142/ef74686e-ebd2-11e6-83ee-a01d92ee3585.png)
![screen shot 2017-02-05 at 6 33 36 pm](https://cloud.githubusercontent.com/assets/13501166/22630143/ef787cec-ebd2-11e6-8f49-aab32385f7e2.png)

**Comment by garfield69** [comment] 2017-02-05 22:59
@lonelyfairie  terrific feedback, thank you. I will look into all your findings.     
A couple of points , FYI.    
- ExtraTorrent will be removed in the next release. ET have changed their encryption sceme **AGAIN** and I am tired of maintaining it. The Team consensus is that since we have plenty other Search Engines available, ET is just not worth the effort.     
- The Multi-Search Engines option in the **Auto-Download** panel is not implemented, so while you can choose SE, the auto-download still only use the default SE and any Series Custom SE. I think I will hide this section until I finish the supporting code, to prevent confusion.     
- The auto-download multi search engine options is distinct and separate from the multi-search engines options for the torrent dialogues, which you can enable/disable from the **Torrent Search Engines** panel.     

Cheers.

**Comment by lonelyfairie** [comment] 2017-02-06 01:54
Oh I was under the impression there was only one multi search option, kinda like the global quality option which you can then override from the torrent search dialog and the series torrent settings if needed.

Agree about extratorrent, there are sufficient torrent providers as is to have to do extra work for that one.
