### ISSUE TITLE
Unable to use Paste on Mac OSX with duckietv standalone nwjs 0.12.2

### ISSUE THREAD

**Issue by lonelyfairie** [SchizoDuckie/DuckieTV#568] opened 2015-10-05 19:32 UTC
I just realized I can't copy paste to duckie on my mac, is this normal or a bug?
I just tried copy pasting the trakt.tv PIN to duckie and no go, also tried pasting something into the series search bar and again nothing is shown.

**Comment by SchizoDuckie** [comment] 2015-10-05 19:34
Hah, interesting :)

This seems to refer to an nwjs bug https://github.com/nwjs/nw.js/issues/1955 
I hope to have the mac nightlies working soon so that we can verify if this is fixed with nwjs 0.12.3 !

**Comment by garfield69** [comment] 2015-10-05 19:37
no trouble using copy/paste with nwjs on windows...but I've been on 1.12.3 for some time now.

**Comment by SchizoDuckie** [comment] 2015-10-14 21:11
Confirmed, cannot use copy/paste on mac. We'll have to wait for nw.js to fix this though as this is a native binding that should work

**Comment by garfield69** [comment] 2015-10-15 18:43
>Confirmed, cannot use copy/paste on mac.

are you confirming for nwjs mac 0.12.2, or are you saying that 0.12.3 also cannot handle copy/paste?

**Comment by SchizoDuckie** [comment] 2015-10-15 18:56
0.12.3 does not copy/paste.

**Comment by garfield69** [comment] 2017-01-12 23:21
@lonelyfairie  Once you are on the mac nwjs 0.19.x, can you test that you can copy/paste please? Thanks.

**Comment by lonelyfairie** [comment] 2017-01-13 20:52
@garfield69 I just posted on the other issue thread that I am unable to start duckie with nwjs 19.5 sdk version. 
I get this after copying all files to the duckie directory and trying to open the app:
![screen shot 2017-01-13 at 5 47 30 pm](https://cloud.githubusercontent.com/assets/13501166/21945257/1229725e-d9b9-11e6-8810-dac2d3b86df3.png)

**Comment by Js41637** [comment] 2017-01-13 20:57
Pretty sure we're using 0.18.6, not 0.19

**Comment by SchizoDuckie** [comment] 2017-01-13 21:27
Mac build seems borked currently. Still looking in to that but my vm needs
some tlc

Op 13 jan. 2017 9:58 p.m. schreef "Js41637 ftw" <notifications@github.com>:

**Comment by garfield69** [comment] 2017-01-13 21:31
@Js41637  the Nightly are currently using 0.19.1, but on my sandbox I've got 0.20.beta2 (admittedly its windows x32 and not Mac) running without problems.     
@lonelyfairie  look for a file called `debug.log` in the same directory as the nwjs program, it may contain an explanation for why nwjs did not startup properly.     
I don't have a mac so I can test this for you.     
Try going back a release at a time, you will find the previous releases here https://dl.nwjs.io/

**Comment by lonelyfairie** [comment] 2017-01-13 22:21
So I tried:
SDK versions:
v0.20.0-beta
v18.8
v18.6
v0.17.6
v0.15.4
v0.14.7
v0.14.5

nonSDK versions:
v0.14.5
v0.14.2
v0.18.6

All give the same screen. I am currently trying to re download 14.0 but getting a bad gateway error on the website. 
I update the dev version via github desktop but just in case I downloaded the .zip file and copied all files back trying to make sure I hadn't deleted any other files in the process of exchanging nwjs versions. 

I know that 14.2 was the last I used successfully to run duckie after the failing back ups so I tried that one on purpose but still get the same.
I found some crash logs and hang logs on my mac so I am attaching those as well (I tried to read them but couldn't figure out anything useful).
[Archive.zip](https://github.com/SchizoDuckie/DuckieTV/files/705467/Archive.zip)

**Comment by garfield69** [comment] 2017-01-13 23:00
Ok. lets pause a moment, and think this through.   
If you loaded 0.14.2 which you previously had working, and now it will not start, then that suggests that the problem is not with the  0.14.2 package, but with either the duckietv files or your current mac system state.   
So here is a list of thing for you to try in turn:    

1. try a full shutdown and startup of you mac system, and startup up nwjs 0.14.2    
2. try renaming  folder `~/Library/Application Support/DuckieTV-Standalone` to `~/Library/Application Support/DuckieTV-Standalone-old` so that you start 0.14.2 with a fresh blank storage area.
3. empty the duckietv app folder, load it with the latest duckietv source code, and add the 0.14.2 package over the top.

**Comment by lonelyfairie** [comment] 2017-01-15 02:52
OK, so I had already deleted the ~/Library/Application Support/DuckieTV-Standalone folder before just to test if that was the issue and the folder never came back (to be expected since duckie isn't starting).  So I used CCleaner to delete any caches on the mac and re started,  then deleted the duckie repository from my computer and re cloned it using github desktop, then added nwjs 0.14.2 but I still get that nw.js window instead of duckie. 

I am not sure what is going on with my machine and I agree it is probably not a duckie specific issue and more of a system issue so I need to do some serious digging as to what might have changed since I last was able to run duckie corretcly, remember this whole mess started since I was unable to run nwjs because I was getting that "quit unexpectedly" error before so I started switching nwjs versions. I have to find time to do a full search on the system and probably delete any nwjs files left over from previous runs/installs and then try to start over once again. I will set up duckie 1.1.3 tomorrow with my old backups to have something still running for me and will return to the dev version once I find how to fix nwjs on my machine.
Thanks for all the pointers and I will remember to test out the copy paste once I am back on the dev version and report back. :)

**Comment by lonelyfairie** [comment] 2017-01-17 02:44
@garfield69 I made a mayor cleanup of all nwjs related stuff I could find, I deleted duckietv folder, re downloaded everything and now when I try to run I get this error:

![screen shot 2017-01-16 at 11 43 51 pm](https://cloud.githubusercontent.com/assets/13501166/22005894/af76370c-dc45-11e6-9418-b84560aa0670.png)

**Comment by garfield69** [comment] 2017-01-17 03:21
Basically this means that nwjs found a package.json file, but it is not the one from the latest duckietv development source (1.1.4 wip).     
Using a plain text editor, open the package.json in the folder that contains the nwjs program that you are launching. It should look like this: https://github.com/SchizoDuckie/DuckieTV/blob/angular/package.json     

see at line 108 ` "default_locale": "en"` , this is what nwjs is looking for, and for some reason the nwjs program that you launched did not find it.     

IF your package.json looks like the one from duckietv, then this means the nwjs program is not residing in the correct folder structure, or if you are using a shortcut to start the program, then the shortcut properties are not pointing to the correct working folder or program location.
Or there is some other reason, which I can't figure out from what little I know of macs.     
If your package.json does not look like the one from duckietv, then where did you put the duckietv source code, and where did you put the nwjs archive suite you are launching?

Of course, all of the above applies to windows, the only platform I am qualified to support. I do not have a mac, so I cannot be sure that nwjs for that platform works in the same way. :-(

**Comment by lonelyfairie** [comment] 2017-01-17 13:54
Ok so I checked the file and all was ok, I was using nwjs 14.2 for testing but after reading this:
https://github.com/SchizoDuckie/DuckieTV/issues/638
And seeing you where getting this error with v14.x I went ahead and put nwjs (no sdk tools) v19.5 and duckie started up correctly.

So I went ahead and tested out copy/paste and it worked fine, so yay that! 🎉 

thanks for your help @garfield69 you are awesome :)

**Closed** 2017-01-17 14:40 UTC
Labels: 2 - Working, bug, Pending Feedback

**Comment by garfield69** [comment] 2017-01-17 17:17
Excellent! Good work persevering through all that trial-and-error torture. :+1:

**Comment by lonelyfairie** [comment] 2017-01-18 14:38
Are you kidding me? As if I could live my life without DuckieTV now... no way!
