### ISSUE TITLE
Some series are marked with wrong Season

### ISSUE THREAD

**Issue by orien2k** [SchizoDuckie/DuckieTV#656] opened 2016-03-15 19:28 UTC
Hello, 

I found out some series are marked with wrong season. For example: American Dad S13 there is nothing you need to search American Dad S12 to find the new episodes.

**Comment by Js41637** [comment] 2016-03-15 19:45
Unfortunately this is an issue with TheTVDB/Trakt.TV, someone has either entered the data incorrectly or new releases are getting put under the incorrect name. Looking on TheTVDB for American Dad shows Season 13 looks to be the latest however on torrent sites they still seem to be at season 12.

**Comment by garfield69** [comment] 2016-03-15 19:54
XEM has the correct cross-reference matchings, and DuckieTV uses XEM for its Trakt.TV-to-scene-torrent-names cross-reference.

So on DuckieTV, clicking on the *American Dad S12E15* episode, on the DuckieTV episodes list page, and then clicking on the *search-for-download* icon, brings up a torrent search dialog with a query for *American Dad S11E15*, which is the correct scene torrent name.
:-)

**Comment by garfield69** [comment] 2016-03-15 19:56
unfortnately, DuckieTV is not getting the latest XEM tables, so it is missing the season 13 cross references, which is a problem. issue #645 was raised to fix this.

**Comment by garfield69** [comment] 2016-03-15 19:58
closing as a duplicate of 645.

**Closed by garfield69** 2016-03-15 19:58 UTC
Labels: duplicate
