### ISSUE TITLE
Still stuck on 02 08 for Browser Action Mode

### ISSUE THREAD

**Issue by GraveDigger1** [SchizoDuckie/DuckieTV#1260] opened 2020-05-29 11:33 UTC
I know I've mentioned it before but til it's fixed I will keep mentioning it, and that is we need to have the manually installable Browser Action and New Tab extensions updated when the Stand Alone version is AND posted here on Github just like the Stand Alone is.  Well over half of us do not have a VPN on our desktops so need the browser extension.

**Comment by garfield69** [comment] 2020-05-29 19:31
duplicate of #1233 

An alternate option to depending on the Google Chrome Store, is to install the latest Nightly Chrome Extension manually via the Developer mode.
- download DuckieTV-yyyymmddhhmm-chrome-browseraction.zip file from https://github.com/DuckieTV/Nightlies/releases and unpack it to a folder of your choice.
- access the Chrome Browser Extensions page at chrome://extensions/
- enable **Developer Mode** (top Right switch on the extensions page)
- click on the load unpacked button
- and select the folder that contains the manifest

the Nightly action you just install should be available as the upside down Duckie icon near the right of the address bar

**Closed as completed by garfield69** 2020-05-29 19:31 UTC
Labels: duplicate
