### ISSUE TITLE
Unable to connect to qBittorrent

### ISSUE THREAD

**Issue by TiraelSedai** [SchizoDuckie/DuckieTV#1022] opened 2018-01-12 19:12 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Win

**Describe the problem you are having and steps to reproduce if available**
Can't connect to QBittorrent Web API.
I'm able to log in when sending POST from Fiddler.
qBittorrent version 4.0.3

**Attach any DuckieTV statistics or Developer Console logs if available**
Status: Not connected

Error: {"data":"","status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"headers":{"Content-Type":"application/x-www-form-urlencoded","X-Forwarded-Host":"chrome-extension://bagblfnohpiddokbpaacecffdboomafe","Accept":"application/json, text/plain, */*"},"url":"http://localhost:8080/login","data":"username=qbadmin&password=mypwdhere"},"statusText":"Unauthorized"}

**Comment by garfield69** [comment] 2018-01-12 21:38
Duplicate of #1009
Yes, qBt made a change in 4.0.3 that broke the DuckieTV qBt client interface. qbittorrent/qBittorrent@b827761 fixes this problem, which will be included in the next qBt release, whenever that gets published.
The problem cannot be fixed by DuckieTV, so 4.0.2 is the current compatible client.

**Closed as completed by garfield69** 2018-01-12 21:38 UTC
Labels: duplicate
