### ISSUE TITLE
Shows not remaining "Watched"

### ISSUE THREAD

**Issue by TVGuy411** [SchizoDuckie/DuckieTV#882] opened 2017-03-25 10:45 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Browser Action

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
v3017.3.24.511

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 64 bit

**Describe the problem you are having and steps to reproduce if available**
Shows previously marked as downloaded and watched randomly return to downloaded status.  This occurs when the extension is closed then re-opened or if it remains open for an extended period of time.  If I mark them watched again, I can see it writing to the database but closing and reopening will result in random programs being returned to downloaded only status.
[Duckie Database.zip](https://github.com/SchizoDuckie/DuckieTV/files/869928/Duckie.Database.zip)
![duckie before](https://cloud.githubusercontent.com/assets/26670555/24321599/88787b54-1126-11e7-8ce8-bda20c2b6918.png)
![duckie after](https://cloud.githubusercontent.com/assets/26670555/24321602/8e6fd52a-1126-11e7-9971-53c45583d83e.png)

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2017-03-25 18:23
Thanks for reporting.     
I am able to replicate your findings.     

Basically the problem seems to be with the calendar's *mark all watched* routine.     
If any of that days episodes are already marked as watched, then clicking on *mark all watched* will flip those to un-watched, while setting the rest to watched.     
If all episodes of that days are un-watched, then *marking all watched* correctly set all to watched.    
And if all of the episodes of the day are already marked a watched, then using the *mark all watched* will set them all to un-watched.     
But if you manually click on the individual *watched* buttons for any episode to set them to watched, those episodes remain watched as intended.     
Time to dig into the code.    
[edit]     
By switching to use the foreground CRUD adaptor I resolve the issue. so Now I just got to figure out why the background CRUD adaptor is behaving this way.

**Comment by garfield69** [comment] 2017-03-25 19:33
Ah, but wait. The plot thickens. I should have said, I can replicate the problem using your DB. But using my DB I don't get the problem. So, actually, it's time to look at your DB to see what is different about it.

**Comment by garfield69** [comment] 2017-03-25 23:19
@SchizoDuckie  just to keep you in the loop: the *background CRUD adaptor* appears to be lying to me.     
I enabled some logging to track what information the BGcrudA was writing to the DB, and comparing it with what was actually in the DB afterwards, using the *DB Browser for sqlite* program.      
I added the following 2 console.debug to the CRUD.entities.js Episode.markWatched routine:    
``` javascript
    markWatched: function(downloadedPaired, $rootScope) {
        if (typeof downloadedPaired === 'undefined') {
            downloadedPaired = true;
        }
        console.debug('B',this.ID_Episode,this.watched,this.watchedAt,this.downloaded);
        this.watched = 1;
        this.watchedAt = new Date().getTime();
        if (downloadedPaired) {
            // if you are marking this as watched you must have also downloaded it!
            this.downloaded = 1;
        }
        return this.Persist().then(function() {
            if ($rootScope) {
                $rootScope.$broadcast('episode:marked:watched', this);
            }
            console.debug('A',this.ID_Episode,this.watched,this.watchedAt,this.downloaded);
            return this;
        }.bind(this));
    },
```
and also enabled CRUD.DEBUG = true in all the relevant places.      

![image](https://cloud.githubusercontent.com/assets/6933240/24326791/6c46b806-121b-11e7-8f7d-3c5e773fa0bf.png)
The above shows the following sequence:      
0. Began with the calendar like this:
![image](https://cloud.githubusercontent.com/assets/6933240/24326859/69b98e86-121d-11e7-8154-7d48d4531480.png)     
then clicked on the *mark-all-watched* link     
1. the entry into *episode.markWatched* shows the before-state of the episode id=4845  **episode.watched=1**     
2. the CRUD.DEBUG reporting that only the *episode.watchedAt* was intended to be changed      
3.  the exit out of *episode.markedWatched* confirming that the *episode.watchedAt* in memory was changed     
4. however, the DB itself after the i/o shows that not only was the *watchedAt* changes, but also that *watched* was altered from 1 to **0**. !!!      
5. Calendar after looked like this:
![image](https://cloud.githubusercontent.com/assets/6933240/24326874/a2d29046-121d-11e7-8e2b-132ead15296d.png)
6. but if I refresh the calendar is now looks like this:
![image](https://cloud.githubusercontent.com/assets/6933240/24326879/c8d6d1b2-121d-11e7-809a-922fa5d251ef.png)

This is unexpected.      
Testing with the Foreground CRUD adaptor shows the expected behaviour.      
I will continue to dig deeper later tonight, but it is a puzzle to me right now, and I need a break.

**Comment by garfield69** [comment] 2017-03-26 06:26
**Cracked it**.     
The *Background Adaptor* is applying the Episodes table *defaultValues* set (which contains watched = 0) during the episode object update, while the *Foreground Adaptor* does not.     

So I was able to bypass this problem ticket issue by removing from the CRUD.entities the `defaultValues {watched = 0}` set from the Episodes table definition.     

We already code a default value for the *watched* element in the Episodes table CREATE statement, so technically, the *defaultValues* set is redundant in this case.

@TVGuy411  when the next Nightly is pushed out, you should find that the *mark-all-watched* link on the calendar should start working properly again.      
Please test and confirm. Thanks.

**Comment by garfield69** [comment] 2017-03-26 07:08
tested on nightly 20170326

**Closed as completed by garfield69** 2017-03-26 07:08 UTC
Labels: bug, 3 - Done, Testing Completed
