### ISSUE TITLE
Chrome  Version 119.0.6045.124 not functioning with Duckie TV

### ISSUE THREAD

**Issue by syphondog3** [SchizoDuckie/DuckieTV#1400] opened 2023-11-12 07:21 UTC
Hello!

After chrome updated itself to the latest version (119.0.6045.124)), the version of DuckieTV that I had stopped working.

I downloaded a new version ofNew Tab DuckieTV, but it is not working.

Any suggestios please?

Thank you

**Comment by garfield69** [comment] 2023-11-12 07:23
read https://github.com/SchizoDuckie/DuckieTV/issues/1399#issuecomment-1789353212
closing as duplicate of #1399

**Closed as completed by garfield69** 2023-11-12 07:23 UTC
Labels: duplicate

**Comment by syphondog3** [comment] 2023-11-13 17:14
Thank you for directing me there --

I hope that chrome://flags/#web-sql-access is not removed. Stupid that Chrome is making all these unnecessary changes.

Thank you Garfield! It is working again!
