### ISSUE TITLE
DTV remembers previous torrent client and keeps using it

### ISSUE THREAD

**Issue by VulcanTourist** [SchizoDuckie/DuckieTV#1284] opened 2020-11-14 17:12 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
202011071931 (Garfield's build)

**What is your Operating System (Windows, Mac, Linux, Android)**
Windows 10 x64 rev. 2004

**Describe the problem you are having and steps to reproduce if available**
Previously I was using uTorrent as a BitTorrent client, and had configured DuckieTV to control it.  Recently I decided to attempt to use qBittorrent again, and was successful finally in getting it to work with DuckieTV.  All was good!  Or so I thought....

Yesterday, we had a very brief power failure.  Later, after restarting my system, DuckieTV initiated some downloads, but it didn't use qBittorrent to do it: instead it launched uTorrent again and send the commands to it!  I checked the configuration, and DuckieTV was in fact still configured to use qBittorrent, but it was ignoring that and instead back-dooring into uTorrent because of the previous link that it was remembering.

Just now I switched DuckieTV back to uTorrent and told it to forget/delete the integration with it.  I hope this will cure the misbehavior, but doing this shouldn't have been necessary and is very unintuitive.

**Comment by garfield69** [comment] 2020-11-14 17:51
Very unlike that Dtv forgot. Bu I can see how it might appear that this is what is happening. Let me explain.

If Dtv is configured to use qBt, but when it submits torrents they are going to uTorrent, then the issue is that Dtv was not connected to qBt when it did the submissions.

When a connection to qBt is not established, Dtv assumes that this is most likely due to qBt not being started.
So Dtv tries to use the alternate method of submission, which is to pass the magnets/torrents via the Chromium/OS file association method. 
The idea is that this will cause the OS to launch qBt if its not active, and so get things going again.
It is assumed that because qBt was the preferred client, that when it was installed qBt would have created the file associations for itself.

Bot if your machine has still got magnets/torrents associated with uTorrent then that is what you are seeing.

So the solution is two part:
- Ensure Dtv is connected to qBt: access Dtv qBt 3.2+ integration panel and check that the connection is completed.
- Access the qBt app and set up the file associations. You may need to use the qBt installer, I don't know, I'm not a regular qBt user. 

To test file associations, use a browser and access a magnet and see which torrent-client gets it.

Oh, and be sure to have Dtv Settings > Torrents > Torrents Parameters disabled.

**Comment by VulcanTourist** [comment] 2020-11-15 19:05
I checked the file associations in both and found some conflict there, as
you suggested.  I will monitor it to see if that was the entire issue.
qBittorrent was connected to DTV at the time of the issues, so it wasn't
that.

I have had "Torrent Parameters" enabled, though I don't recall if that was
a conscious choice of mine.  I don't think I fully understand the effects
of that setting.

**Comment by garfield69** [comment] 2020-11-15 19:15
>I have had "Torrent Parameters" enabled, though I don't recall if that was
a conscious choice of mine.  I don't think I fully understand the effects
of that setting.

The torrent parameters settings was a Dtv optional attempt to allow users to get a popup sent by the torrent client, where they could customise the torrents being loaded to the client, by allowing the user to adjusting file paths and trackers and what ever else the apps allowed.
However, this popup is usually not available via the API interface of the torrent clients.
It is usually invoked via the chromium/OS file association link.

But using this option conflicts with the Dtv auto-downloader, since you are in effect, changing the auto-download into a semi-manual, as all torrents submitted this way will not auto-start but wait until the popup for each torrent is acknowledged and dealt with.
And since Dtv is not using the API when this option is enabled, Dtv cannot keep track of the torrent progress as the hashkey is not available to link the torrent and the episode.

**Comment by VulcanTourist** [comment] 2020-11-15 20:01
Ah... then I suspect that having this enabled is why download completion
wasn't being recognized when seeding was still taking place.  Glad I just
changed it!

**Comment by garfield69** [comment] 2020-11-23 03:06
Closing, presumed resolved. Can always re-open if OP reports issue unresolved.

**Closed as completed by garfield69** 2020-11-23 03:06 UTC

**Comment by VulcanTourist** [comment] 2020-11-23 20:28
Sorry, I meant to follow up but didn't remember when it was useful.
Correcting the associations seems to have been all that was required, thank
you.  DuckieTV also no longer gets confused by post-download seeding, so
that was an added bonus of the effort to resolve this.

**Comment by garfield69** [comment] 2020-11-23 20:38
Thanks for following up. Cheers.
