### ISSUE TITLE
No longer updating and all images replaced with the DuckieTV duck

### ISSUE THREAD

**Issue by Slaughterhouserock** [SchizoDuckie/DuckieTV#793] opened 2016-11-11 10:26 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Chrome Extension (New Tab)

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
...v1.1.3

**What is your Operating System (Windows, Mac, Linux, Android)**
...Windows 7 Ultimate x64

**Describe the problem you are having and steps to reproduce if available**
...This past week, I noticed that it has stopped updating and all images have been replaced with the duck logo.  Tried re-installing, still nothing.

**Attach any DuckieTV statistics or Developer Console logs if available**
...Unique tracking id: 75791c45-6a59-72ce-b95f-6e5aba1ba83b

**Comment by garfield69** [comment] 2016-11-11 17:05
This is due to Trakt.TV terminating their image service beginning 1st November 2016.     
For more details read https://apiblog.trakt.tv/trakt-api-images-56b43c356427     
A new release will be published once we have completed a solution.     
You can follow the progress with https://github.com/SchizoDuckie/DuckieTV/issues/780      
Closing this ticket as a duplicate of 780.

**Closed by garfield69** 2016-11-11 17:05 UTC
