### ISSUE TITLE
Problem importing from trakt

### ISSUE THREAD

**Issue by knowair** [SchizoDuckie/DuckieTV#877] opened 2017-03-20 10:24 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...Standalone Windows 64 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
... Nightly 2017/03/18

**What is your Operating System (Windows, Mac, Linux, Android)**
...win10

**Describe the problem you are having and steps to reproduce if available**
... cannot import shows or collected shows

A New install of DTV, verified trakt account no problem, click on the option to do a full import, and although the screen loads with the empty poster boxes and yellow spinning icon. it did not move on from there.

I've done this 3 time now! 

first time i did a data wipe and re-connected, needed to force close after few hours, tried using the "just import Collection" option and had to force close after a few hours of spinning yellow icons

The second time i re-installed DTV with the latest nightly  tried with and without the "Collection only" ticked, and had to force close each time

The third time i reinstalled again and revoked Duckie's trakt add-on authority to force it to re-auth from scratch. tried with and without the "Collection only" ticked, and had to force close each time

this last time I left it 14 hours! by the evening some of the posters did appear and in the bottom right the green database updating panel showing 0/8 and stopped there (I have hundreds of shows on trakt), so i left it overnight, after 24 hours the poster boxes and green update panel were gone but no shows were added to duckie.

--

Adding shows manually works fine, so i'm still happily using duckie! but would like to be able to link to trakt.

--

Also, tried a fresh install on android and cannot auth trakt, duckie opens it's own browser window to get the auth code and when you click back the duckie page re-loads and you cannot enter the code.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by garfield69** [comment] 2017-03-20 17:23
Thanks for the report.     
I'll set up my sandbox and begin some trial tests to see if I can replicate your problem and trace the issue.    
  
I am going to split the android trakt.tv issue into a new ticket so that it can be tracked, managed and closed separately.
[Edit] #878 created for the Android Trakt.TV auth report.

**Comment by garfield69** [comment] 2017-03-21 07:11
I am sorry, but I cannot replicate your problem.     

On my sandbox, starting with a fresh install of Windows 7 x32 DuckieTV Standalone Nightly v201703200830, I did the following:     

- Deleted the previous Nightly's data area folder `C:\Users\<username>\AppData\Local\DuckieTV-Standalone` to ensure a clean start     
- start up DuckieTV and wait about 30 seconds for the basic first time initialisation to complete     
- from the *you don't have any series yet!* panel, clicked the *connect DuckieTV to your Trakt.tv account* button    
- clicked the *authorise DuckieTV to use your Trakt.tv account* button    
- pasted the Trakt.tv pin into the *your Trakt.tv PIN* input box      
- clicked on the *login to Trakt.tv* button      
- the *Trakt.tv import* panel extension is displayed     
- pressed the **F12** ket to open the *Development Tools* panel, and clicked on the **console** tab to view the log so I can track progress and errors     
- clicked on the *import shows from Tratk.tv* button     
- once the poster icons with the spinners show up, minimise the DuckieTV page (to speeds things along)    
- monitor the activity looking for the following milestones:     
```
2017-03-21 19:40:13.885 Mapping currently added series
2017-03-21 19:40:15.264 Fetched V2 API User Shows:  [Object…]
2017-03-21 19:40:15.272 Found 237 shows in users collection
2017-03-21 19:40:16.158 Fetched V2 API watched results:  [Object...]
2017-03-21 19:40:16.166 Found 177 shows in users watched episodes collection
2017-03-21 19:42:33.015 Done adding watched shows, adding watched episodes to DB
2017-03-21 19:43:13.017 Successfully marked all episodes as watched
2017-03-21 19:43:57.662 Firing series:recount:watched
```     
- the import took about 4 minutes. Maximised DuckieTV and examined the *About* statistics to confirm that everything was imported.    
```
DB Series: 237
DB Seasons: 1085
DB Episodes: 15773
```

Presumably your imports are being interrupted by some error condition or event, and looking at the log may be the only way to shed some light as to why this is not working for you.     

If on the console log, you right-click your mouse over one of the messages with a 
![image](https://cloud.githubusercontent.com/assets/6933240/24136122/3202506c-0e72-11e7-9769-54a8c80d0fe3.png) on the left of the text, you should get the option to *save as...*, so you can dump the log into a text file and uploaded here if you want us to analyse the content for you.

**Comment by knowair** [comment] 2017-03-21 12:05
thanks, i'll get the console logs for you later on, fuck knows what i've done to cause this!! :)

**Comment by knowair** [comment] 2017-03-21 14:46
[bagblfnohpiddokbpaacecffdboomafe-1490106975885.zip](https://github.com/SchizoDuckie/DuckieTV/files/858463/bagblfnohpiddokbpaacecffdboomafe-1490106975885.zip)

this log was save about 30 mins after clicking the import option

**Comment by knowair** [comment] 2017-03-21 14:46
dtv looks like this after the log is saved: 
![dtv30m](https://cloud.githubusercontent.com/assets/9417645/24152997/2aecb326-0e45-11e7-89ec-7f800511c2b1.png)

**Comment by knowair** [comment] 2017-03-21 16:27
OK this is weird

2hours later i have just logged in to see the watched episodes updated but not teh collected/dowloaded

i'm not sure what i did differently but this time it's at least part imported some information after ~2.5 hours

Any idea why only the watched episodes and not the collected episodes would import

this pic should show almost all of the shows as collected/downloaded, but it's only got the ones i've actually watched

![only-watched](https://cloud.githubusercontent.com/assets/9417645/24157909/a828f3c4-0e52-11e7-8185-c0859abb25aa.png)

**Comment by knowair** [comment] 2017-03-21 18:59
Sorry forgot to get a log for that then so I've done another import to get one

Changed the extention to Txt to upload 

[bagblfnohpiddokbpaacecffdboomafe-1490122118698.txt](https://github.com/SchizoDuckie/DuckieTV/files/859333/bagblfnohpiddokbpaacecffdboomafe-1490122118698.txt)

**Comment by garfield69** [comment] 2017-03-21 19:42
Thanks for the logs.     
So this time I see that your import completed, as all 8 milestones are in the log.     
Clearly something was interrupting your previous imports.... perhaps an issue with your regions Trakt.TV server or maybe when you set the client to *Transmission* the first time initialisations were interrupted.    
This causes a reboot of DuckieTV, and if done too soon after startup it might have caused problems...I don't know.    
 
Have you checked with the *About* page statistics to see of your *Series* count is 258?     

After your last post I went back to take a look at the actual state of the episodes in the database of my sandbox, and I see what you mean.     
The episodes from the *Collection* have been imported but are not marked as downloaded, oops.     
The episodes that were marked as watched on Trakt.TV have been set to watched, which is good.     
Looking back at the changelog I see that the Trakt.TV import was refactored 6 month ago, but we obviously missed this in our testing.     

I'll work on a fix for this.

**Comment by knowair** [comment] 2017-03-22 14:29
Sorry for dragging you down a bit of a rabbit hole with this one.

Massive thanks, as always, for your awesome, patience, support!

Long live Duckie!

**Comment by garfield69** [comment] 2017-08-09 19:48
closing as a duplicate of #933 as that one is more on topic.

**Closed as completed by garfield69** 2017-08-09 19:48 UTC
Labels: bug, duplicate
