### ISSUE TITLE
qBittorent 4.03 breaks integration

### ISSUE THREAD

**Issue by obo78** [SchizoDuckie/DuckieTV#1016] opened 2017-12-24 13:07 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
Standalone
**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
201712230130 nightly

**What is your Operating System (Windows, Mac, Linux, Android)**
Win 10 64bit
**Describe the problem you are having and steps to reproduce if available**
qBittorent integration broken in new version 4.03.  Throws "Not connected" error.   Same error if Use Authorization is unchecked.  DuckieTV isn't allowing me to copy and paste the error, but it's a 401 and looks like the localhost url is now "unauthorized"  Double checked and reset qBittorent web login credentials with no success.

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by qharley** [comment] 2017-12-24 21:02
I can confirm this behaviour.  
DuckieTV v 1.14
qBittorrent v 4.0.3
Ubuntu Linux 16.04.3

**Comment by garfield69** [comment] 2017-12-25 17:07
Duplicate of #1009
Yes, qBt made a change in 4.0.3 that broke the DuckieTV qBt client interface. qbittorrent/qBittorrent@b827761 fixes this problem, which will be included in the next qBt release, whenever that gets published.
If you cannot wait for the next release, then go back to 4.0.2 to restore access.

**Closed as completed by garfield69** 2017-12-25 17:07 UTC
Labels: duplicate
