### ISSUE TITLE
Web Interface Request

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#783] opened 2016-10-15 14:21 UTC
Can you please add support for a web interface, so that you can install DuckieTV on a seed box alongside your torrent client.

**Comment by SchizoDuckie** [comment] 2016-10-15 14:23
2 op r

Op 15 okt. 2016 4:21 p.m. schreef "zero77" <notifications@github.com>:

**Comment by garfield69** [comment] 2016-10-15 17:20
closed as duplicate of #678

**Closed by garfield69** 2016-10-15 17:20 UTC
Labels: duplicate
