### ISSUE TITLE
I18n template strings untranslated in the online version?

### ISSUE THREAD

**Issue by mateon1** [SchizoDuckie/DuckieTV#497] opened 2015-07-10 12:59 UTC
Sorry if the title isn't clear.

The site doesn't seem to replace any template strings with translations. The site is pretty unusable.

![](http://i.imgur.com/Yg2dtgM.jpg)

I'm using Google Chrome 44.0.2403.61 (beta) on Windows 7. This happens regardless if locale is set to English US or English UK (SETTINGS/DISPLAY/locale/us and SETTINGS/DISPLAY/locale/uk).

(Can't find any equivalent to CONTRIBUTING.md, so don't know what info is needed for a bug report)

**Comment by garfield69** [comment] 2015-07-10 18:05
duplicate of #496

**Comment by SchizoDuckie** [comment] 2015-07-10 18:41
There is something with the jekyll that doesn't like underscores in directory. I believe the solution was to add a .nojekyll file in the root.

![image](https://cloud.githubusercontent.com/assets/111710/8626247/fec38106-2743-11e5-868d-f5167985261f.png)

**Comment by DuckieTV** [comment] 2015-07-10 18:44
hmm so apparently that file is already there. maybe the interface changed.

Anyway, there is this android bug too: https://code.google.com/p/android/issues/detail?id=5343
Which prevents us from deploying the codebase 1:1 to an apk. I will try to figure out away around that, perhaps having an _locales directory (as dictated by chrome extensions) and a locales directory for non-chrome extensions.

I will see if I can make this a part of the build step.

**Comment by SchizoDuckie** [comment] 2015-07-10 19:19
Possibly interesting for in the debug info section: 
chrome.i18n.getUILanguage()

**Comment by SchizoDuckie** [comment] 2015-07-15 18:21
I just fixed this by pushing the cordova compatible version :) I also added this to the build script so that this happens automagically from now on.

One Warning though: **DO NOT** connect your torrent client or enter any credentials on the online hosted version because all data will be proxied!

**Closed** 2015-07-15 18:23 UTC
Labels: 1 - Ready, bug

**Comment by garfield69** [comment] 2015-07-15 18:46
Wondering if it is worth adding code to recognise we are in DEMO mode and disable the torrent client connections or trackt.tv logins?

**Comment by DuckieTV** [comment] 2015-07-15 18:57
That could be a good idea :) We can just hide those UI components with with
a special getSetting key
