### ISSUE TITLE
category and status filter dropdowns in serieslist no longer populate on opening serieslist -> filtering

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#471] opened 2015-06-22 22:49 UTC
But they do show on second time, after closing the serieslist and reopening it.

**Comment by garfield69** [comment] 2015-06-22 23:23
Huh. Not seeing this. What is the sequence of mouse/key strokes please?

**Comment by SchizoDuckie** [comment] 2015-06-22 23:30
open serieslist (clicking heart), after page refresh, open the filters, click one of the 2 dropdowns, they are both not populated.

Click a serie, so that the sidepanel opens, click the dropdown again and it's populated.
a $scope.$applyAsync missing somewhere?

**Comment by garfield69** [comment] 2015-06-22 23:31
so you are doing a browser refresh while the library page is open?

**Comment by SchizoDuckie** [comment] 2015-06-22 23:32
yeah

**Comment by garfield69** [comment] 2015-06-22 23:34
wonder if it is something to do with the translate-once I added for translating the pull-down lists.

**Comment by SchizoDuckie** [comment] 2015-06-22 23:37
most likely yes :)

**Comment by garfield69** [comment] 2015-06-22 23:46
on that note I have noticed recently that when I start DuckieTV 1.0.2 DEV I sometimes get no translated text. A Browser refresh Refresh or using the settings/language repopulates.
Could be an issue with the current version of angular-translate.min.js we are using perhaps.

**Comment by garfield69** [comment] 2015-06-23 03:32
OK. by painstakingly reverting commits in my sandbox, I have backtracked to the point where the  library filter's status/genre drop-down still work after a browser refresh.
and the answer is...
within these pair of commits (they are dependant on each other for a working commit)
d865a2743b2a33d6152336a19890158a96f6bb93 Fix issues with last commit
e5d2387f0cda0d9a1732760dbcd7e2c16595fe3d Testing changes to filter toolbar pushing page down re: #465

I suspect the problem lies with line 25 in templates\serieslist\tools\favorites.html
```HTML
<div ng-controller="localSeriesCtrl as localFilter" class="filtertools" collapse="!serieslist.isFiltering">
```
So after a browser refresh, is serielist.isFiltering no longer accessible?

**Comment by Js41637** [comment] 2015-06-23 04:46
I don't really know what's going on in here but the problem I told @SchizoDuckie about before is the genres and status lists aren't ready when the serieList load if you load straight onto it (or even opening it too quickly on calendar load) so the dropdowns will be empty. Closing and opening the serieslist however correctly populates the lists.

This has always been an issue with the SeriesList. Not related to this issue specifically but others as well. SeriesList loads too fast before anything else on Page Load when nothing is ready.

For instance loading straight onto the 'Add a serie' page the 'You have no Series' alert will always show because it loads before FavoritesService.

**Comment by garfield69** [comment] 2015-06-23 08:05
what is confusing me is why app.routes is not being used to manage the matching of controllers and templates...I thought that was its job ?
Also, why does templates\serieslist\tools\favorites.html  need `ng-controller="localSeriesCtrl as localFilter"` at line 25 instead of relying on app.routes to do it?
And why does app.routes line 122  have `templateUrl: 'templates/serieslist/searchresults.html'` when that template was deleted by dd69ee5cd3660eb63f15a5a8a9a1b5427c8a6a01?
And line 116 has `templateUrl: 'templates/serieslist/tools/localfilter.html',` when that was deleted by e5d2387f0cda0d9a1732760dbcd7e2c16595fe3d.
app.routes and this whole controllers and templates pairing thing has become a little unstuck IMO.

**Comment by Js41637** [comment] 2015-06-23 08:12
That's because its not used anymore, @SchizoDuckie changed filtering to be done on the same page when he did the poster stuff. So the router is not even used anymore so the controller has to be loaded manually.

**Comment by Js41637** [comment] 2015-06-23 08:15
The filtering controller could probably be moved into the SeriesListCtrl now seeing as it's no longer it's own page.

**Comment by garfield69** [comment] 2015-06-23 08:20
Well clearly I did not get that memo ;-)

So once the dust settles and all these serieslist changes are complete, I hope one of you two cleans up app.routes.
I can then begin to re-learn how it all pieces together again, because I don't mind telling you, I am lost in this controller/template routes maze right now.
  ----- Original Message -----

**Comment by SchizoDuckie** [comment] 2015-06-23 08:40
Understandable. I hope to simplify things some more. In the process of
routing most of the things via the app.routes i went a bit too far and made
things harder on ourselves than neccesary (wiht for instance the filters)
For now the only thing changed is that the local filter route is no longer
relevant.

**Comment by SchizoDuckie** [comment] 2015-06-23 20:50
Works like a charm now! Thanks!

**Comment by garfield69** [comment] 2015-06-23 21:09
Uh, no it does not. the problem of the library filter drop-downs not working after a browser refresh is still outstanding. Please confirm?

**Comment by SchizoDuckie** [comment] 2015-06-23 21:11
Yeap. my  bad. i forgot the refresh step.

**Comment by SchizoDuckie** [comment] 2015-06-25 22:28
Please confirm the waitForInitialization on the favorites root state fixes this :+1:

**Comment by garfield69** [comment] 2015-06-25 22:36
Confirmed. :smile:

**Closed** 2015-06-25 22:37 UTC
Labels: 3 - Done, bug
