### ISSUE TITLE
Only magnet link works to initiate downloads

### ISSUE THREAD

**Issue by timwithtots** [SchizoDuckie/DuckieTV#1141] opened 2019-01-13 19:09 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**

Standalone 

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**

DuckieTV v1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
Win10 Pro

**Describe the problem you are having and steps to reproduce if available**

Over the last two weeks DuckieTV will a download has been initiated and sent to qBittorrent however nothing shows started/queued in qBit.  I can then click the magnet link within DuckieTV and it will initiate just fine in qBIT however qBit does note the torrent is already queued.  I've checked everything on the lefthand side in qBit to confirm it's not sitting somewhere hidden in the Status/Category/Tag etc area.  All other links work fine when launching qBit and it's just the DuckieTV auto-download and/or clicking the show title/link to initiate the download.  I've uninstalled both clients and removed all traces of the folders/files to no avail.

**Attach any DuckieTV statistics or Developer Console logs if available**

I'll wait for tonights shows to pass and once confirmed it's still happening after the latest uninstall/reinstall I'll provide logs.

**Comment by garfield69** [comment] 2019-01-15 20:35
Most likely a duplicate of #1138
If able, switch back to qBt 4.1.4 or earlier as 4.1.5 broke the DTV connection authorisation.
Also, make sure that duckietv>settings>torrent>torrent parameters is set to DISABLED.

**Closed as completed by garfield69** 2019-01-15 20:35 UTC
Labels: duplicate

**Comment by garfield69** [comment] 2019-01-15 20:38
You may also wish to upgrade to the latest standalone  nightly from https://github.com/DuckieTV/Nightlies/releases which has a variety of fixes, (but not for 4.1.5 qBt yet.)
With the nightly you have access to the logs so you can see any relevant error message from the qBt connection.
Use **F12** to open the development tools page, and click on **console** tab to view the log.

**Comment by timwithtots** [comment] 2019-01-15 21:43
Not sure how I didn't even think to try this (installing the previous version...I guess I didn't realize an new on had updated)  Worked like a charm.  Sorry for the miss on my part.
