### ISSUE TITLE
[Feature Request] Autobackup without user intervention

### ISSUE THREAD

**Issue by moswain** [SchizoDuckie/DuckieTV#1423] opened 2024-05-10 10:25 UTC
It would be cool to have DuckieTV auto-backup into a specified folder based on the settings provided.

Backup Timeslots: Daily/Weekly/Monthly
How many backup histories to keep: 3 days/3 weeks/3 months

The dialog box is fine for manual/forced backup. 
But for auto-backups, it just sits there waiting for user interaction.

**Comment by garfield69** [comment] 2024-05-10 17:28
Closing as a duplicate of @1224
See https://github.com/SchizoDuckie/DuckieTV/issues/1224#issuecomment-551387292

**Closed as completed by garfield69** 2024-05-10 17:28 UTC
Labels: duplicate
