### ISSUE TITLE
qbtorrent integration not working

### ISSUE THREAD

**Issue by gralice** [SchizoDuckie/DuckieTV#1019] opened 2018-01-03 22:29 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
...standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmddHHMM)**
...stale 1.1.5

**What is your Operating System (Windows, Mac, Linux, Android)**
...windows 10

**Describe the problem you are having and steps to reproduce if available**
...
can't connect to qbtorrent using 'test' connection.  I get this error:

Error: {"data":"","status":401,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"headers":{"Content-Type":"application/x-www-form-urlencoded","X-Forwarded-Host":"chrome-extension://bagblfnohpiddokbpaacecffdboomafe","Accept":"application/json, text/plain, */*"},"url":"http://localhost:8084/login","data":"username=adm

**Attach any DuckieTV statistics or Developer Console logs if available**
...

**Comment by gralice** [comment] 2018-01-03 22:30
I can get qbtorrents web interface up by going to localhost:8084 with the user and password

**Comment by garfield69** [comment] 2018-01-03 22:47
qBt 4.0.3 have broken their WEBUI when connected by other parties (such as DuckieTV).
So until qBt release 4.0.4 or 4.1 you will need to go back to using 4.0.2 to connect with DuckieTV.
Likely duplicate of #1009

**Comment by gralice** [comment] 2018-01-03 23:22
OK, thanks for the info, I'll downgrade.

**Closed as completed** 2018-01-03 23:26 UTC
Labels: duplicate
