### ISSUE TITLE
Multiple Duckie icons (9) on statusbar Mac

### ISSUE THREAD

**Issue by elvisP** [SchizoDuckie/DuckieTV#625] opened 2016-01-23 11:03 UTC
Hi,

This is how DuckieTV looks on my statusbar (Mac)

![duckiestatusbar](https://cloud.githubusercontent.com/assets/89446/12529873/fea60598-c1c8-11e5-8bc3-d952441960cf.jpg)

**Comment by garfield69** [comment] 2016-01-23 15:21
duplicate of #569

**Closed by garfield69** 2016-01-23 15:21 UTC
Labels: duplicate
