### ISSUE TITLE
Chrome Issues

### ISSUE THREAD

**Issue by AlienProber** [SchizoDuckie/DuckieTV#1300] opened 2021-02-06 19:55 UTC
DuckieTV Browser Action Mode 01312021, AcroLinuxD

I just downloaded the Browser Action nightly from 1/31/2021 and updated Vivaldi, Vivaldi-Snapshot, and Chrome. Both Vivaldi browsers added all my shows from the backup I just did from the previous nightly I had installed, Chrome for some reason will not add more than 152 out of 241 shows. I've done the normal add from backup, I tried adding the backup on top of itself, I tried wiping the database and reloading the backup and nothing works to get all shows listed. I've had to play before to get all shows listed in one or another browser but it has always finally taken. This behavior of not doing it all is brand new. Any ideas on why Chrome might be having an issue when the others aren't. Thanks

**Comment by AlienProber** [comment] 2021-02-09 11:42
@SchizoDuckie @garfield69 want to weigh in  on this? Thanks

**Comment by garfield69** [comment] 2021-02-17 03:59
closing as dupe of https://www.reddit.com/r/duckietv/comments/ldaz3f/chrome_issues/

**Closed as completed by garfield69** 2021-02-17 03:59 UTC

**Comment by AlienProber** [comment] 2021-02-17 11:44
Really this is GitHub NOT Reddit.
