### ISSUE TITLE
PKGNAME

### ISSUE THREAD

**Issue by ZajferX** [SchizoDuckie/DuckieTV#808] opened 2016-12-15 00:36 UTC
**What build of DuckieTV are you using (Standlone / Chrome Extension (New Tab / Browser Action))**
standalone

**What version of DuckieTV are you using (Stable 1.1.x / Nightly yyyymmdd)**
Nightly DuckieTV-11132016-linux-x32.tar.gz

**What is your Operating System (Windows, Mac, Linux, Android)**
Linux

**Describe the problem you are having and steps to reproduce if available**
DuckieTV-11132016-linux-x64.tar.gz still have the PKGNAME issue but on the x86 (32bit) is it fixed ... i have a x64 system and would love to be able to use that version 

**Attach any DuckieTV statistics or Developer Console logs if available**
non available

**Comment by garfield69** [comment] 2016-12-21 07:09
@ZajferX , as you may know, Schizoduckie is in the process right now of rebuilding how his buildbot creates/packages/distributes DuckieTV for all the plaforms we support.    
As far as I know this will include a properly install-able  version of the x64 linux platform.    
I do not have an ETA as yet on a release date.

**Comment by ZajferX** [comment] 2016-12-22 19:43
that answer will suffice :D tnx alot .. will wait patiently

**Comment by garfield69** [comment] 2017-01-09 07:16
closing as a dupe of #801

**Closed by garfield69** 2017-01-09 07:16 UTC
Labels: duplicate
